---
title: "ADM FC"
author: "Megan McMahon"
date: "6/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(readr)
library(tidyverse)
library(gridExtra)
library(tableone)

work_dir <- "~/Box/CogNeuroLab/Aging Decision Making R01/"
results_dir <- paste0(work_dir, "results/rest-activity_and_white_matter_microstructure/")
figs_dir <- paste0(results_dir, "figures/")
data_dir <- paste0(work_dir, "data/")

d <- read_csv(paste0(data_dir, "dataset_2020-10-10.csv")) #includes mean fa from spherical rois 6mm rad
mem <- read_csv(paste0(data_dir, "mri-behavioral/mem_results_06-2020.csv"))
cr <- read_csv(paste0(data_dir, "actigraphy/circadian_measures/7_days/circadian_rhythms_2021-06-14.csv"))
dropcols <- c('actamp','actbeta','actphi','actmin','actmesor','actupmesor','actdownmesor','actalph','actwidthratio','rsqact','fact','fnlrgact')

d <- d %>%
 select(!dropcols, -IS, -RA, -IV, -X1) %>%
  merge(cr, by = 'record_id', all = T) %>%
  merge(mem, by = 'record_id', all = T)

d$Group <- factor(ifelse(as.numeric(d$record_id) < 40000, 0, 1), labels = c("Young Adults", "Older Adults"))

recodeVars = c("vascular_disease", "diabetes", "cancer", "head_inj", 
               "neurologicaldisorders", "psychiatric_do", "sleep_do", "sex", "stroke", "Group")

d[,recodeVars] <- d %>%
  select(recodeVars) %>%
  mutate_if(is.integer, factor) %>%
  mutate_if(is.character, factor)

d %>%
  select(record_id, Group, acc_mean.learning, acc_mean.test) %>%
  head()
```

```{r}
d %>%
  group_by(Group) %>%
  summarise(n = n())

```

## RAR and Sleep Variable Correlations 
```{r}
d %>%
  select(actphi, actamp, sleep_time_mean_sleep, total_ac_mean_active, efficiency_mean_sleep, age) %>%
  corrr::correlate() %>%
  corrr::rplot() + theme(axis.text.x = element_text(angle = 90))
  

```
```{r}
d %>%
  filter(Group == "Young Adults") %>%
  select(actphi, actamp, sleep_time_mean_sleep, total_ac_mean_active, efficiency_mean_sleep, age) %>%
  corrr::correlate() %>%
  corrr::rplot() + theme(axis.text.x = element_text(angle = 90))
```

```{r}
d %>%
  filter(Group == "Older Adults") %>%
  select(actphi, actamp, sleep_time_mean_sleep, total_ac_mean_active, efficiency_mean_sleep, age) %>%
  corrr::correlate() %>%
  corrr::rplot() + theme(axis.text.x = element_text(angle = 90))
```
## fMRI QC report

```{r}
qc <- read_csv("~/Box/CogNeuroLab/Aging Decision Making R01/data/mri/QA report 2021.csv")

qc <- qc %>%
  mutate(full_mem = ifelse((is.na(qc$MemMatch1)) & (is.na(qc$MemMatch2)) & (is.na(qc$MemMatch3)), 1, 0),
         partial_mem = ifelse((is.na(qc$MemMatch1)) | (is.na(qc$MemMatch2)) | (is.na(qc$MemMatch3)), 1, 0)) %>%
  drop_na(Subject)

exclude_fmri <- qc$Subject[qc$partial_mem == 0]
exclude_fmri

qc %>%
  select(Subject, Group, MemMatch1, MemMatch2, MemMatch3, full_mem, partial_mem) %>%
  group_by(Group, partial_mem) %>%
  summarise(n = n())

```

```{r}
d %>%
  filter(! record_id %in% exclude_fmri) %>%
  filter(is.na(actamp)) %>%
  select(record_id, actamp, sleep_time_mean_sleep)

```

## Power Analysis

Resources:
- [Julian Quandt](https://julianquandt.com/post/power-analysis-by-data-simulation-in-r-part-iii/)
- [U Iowa](https://ir.uiowa.edu/cgi/viewcontent.cgi?article=1002&context=pq_pubs)
- [simglm tutorial](https://simglm.brandonlebeau.org/articles/tidy_simulation.html)

```{r}
library(tidyverse) 
library(simglm) 
library(future.apply) 
library(lme4)

n <- seq(4, 1000, 2)
power <- sapply(seq_along(n), function(i)
power.t.test(n = n[i], delta = .2, sd = 1, type = 'two.sample')$power)
```

```{r}
power_df <- data.frame( n = n,
  power = power
)
ggplot(power_df, aes(x = n, y = power)) +
geom_line(size = 2) +
geom_hline(yintercept = 0.8, linetype = 2, color = 'gray30') + 
  geom_vline(xintercept = 700, linetype = 2, color = 'gray30') + 
  scale_x_continuous("Sample Size", breaks = seq(4, 1000, 50)) + 
  scale_y_continuous("Power", breaks = seq(0, 1, .2)) + 
  theme_bw(base_size = 14)

```
```{r}
effect_sizes <- c(.10, .15, .25, .35, .45)
conditions <- expand.grid(n = n, effect_sizes = effect_sizes)
power_curve <- sapply(seq_len(nrow(conditions)), function(i) power.t.test(n = conditions[i, 'n'],
delta = conditions[i, 'effect_sizes'], sd = 1, type = 'two.sample')$power)

```

```{r}
power_curve_df <- bind_cols( conditions,
power = power_curve
)
ggplot(power_curve_df, aes(x = n, y = power)) + 
  geom_line(aes(color = factor(effect_sizes)), size = 2) + 
  geom_hline(yintercept = 0.8, linetype = 2, color = 'gray30') + 
  scale_x_continuous("Sample Size", breaks = seq(0, 1000, 200)) +
  xlim(c(0, 200)) + #because we know we have < 200 subjects
  scale_y_continuous("Power", breaks = seq(0, 1, .2)) + 
  scale_color_grey("Effect Size") +
  theme_bw(base_size = 14)
```

```{r}
simulation_arguments <- list(
  formula = y ~ 1 + sex,
  fixed = list(Group = list(
    var_type = 'factor',
    levels = c('Young Adults', 'Older Adults')
  )),
  sample_size = 40,
  error = list(variance = 1),
  reg_weights = c(0, .2)
)

simulate_fixed(data = NULL, simulation_arguments) %>% 
  simulate_error(simulation_arguments) %>% 
  generate_response(simulation_arguments)
```
```{r}
plan(multicore)

simulation_arguments <- list(
  formula = y ~ 1 + Group,
  fixed = list(Group = list(
    var_type = 'factor',
    levels = c('Young Adults', 'Older Adults')
  )),
  sample_size = 40, #sample size for each group
  error = list(variance = 1),
  reg_weights = c(0, .20),
  replications = 1000,
  model_fit = list(formula = y ~ 1 + Group,
                   model_function = 'lm'),
  extract_coefficients = TRUE
)

replicate_sim <- replicate_simulation(simulation_arguments)
```

```{r}
replicate_sim %>%
  compute_statistics(simulation_arguments, power = TRUE, type_1_error = FALSE, precision = TRUE)

```


```{r}
plan(sequential)
plan(multicore)

simulation_arguments <- list(
  formula = y ~ 1 + group + cr + fc,
  fixed = list(
    group = list(
    var_type = 'factor',
    levels = c('Young Adults', 'Older Adults')), 
  cr = list(var_type = 'continuous', mean = 15.51, sd = 1.75), #acrophase 
  fc = list(var_type = 'continuous', mean = 0, sd = 1)),
  error = list(variance = 1),
  reg_weights = c(0, 0.5, 0.2, 0.4), #cr and fc coefficients from stephanie's paper. age group estimated beta weights for FA and MD were -0.38 and -0.69 in white matter paper. Avg = 0.535, so using that here.
  replications = 1000,
  model_fit = list(formula = y ~ 1 + group + cr + fc, model_function = 'lm'),
  power = list(dist = 'qnorm', alpha = .05), # assume a two-tailed hypothesis test
  extract_coefficients = TRUE,
  vary_arguments = list(sample_size = seq(50, 1000, 50))
)

model_results <- replicate_simulation(simulation_arguments)
```


```{r}
power_results <-
  model_results %>% 
  compute_statistics(
    simulation_arguments,
    power = TRUE,
    type_1_error = FALSE,
    precision = TRUE
  )
```

```{r}
power_results_gr <- power_results %>%
  ungroup() %>%
  mutate(sample_size = as.numeric(as.character(sample_size...4))) %>%
  arrange(sample_size) %>%
  filter(grepl('group', `term...2`))

power_results_cr <- power_results %>%
  ungroup() %>%
  mutate(sample_size = as.numeric(as.character(sample_size...4))) %>%
  arrange(sample_size) %>%
  filter(grepl('cr', `term...2`))

power_results_fc <- power_results %>%
  ungroup() %>%
  mutate(sample_size = as.numeric(as.character(sample_size...4))) %>%
  arrange(sample_size) %>%
  filter(grepl('fc', `term...2`))
```

```{r}
ggplot(power_results_gr, aes(x = sample_size, y = power)) +
  geom_point(size = 1.5, color = 'gray40') +
  geom_hline(yintercept = 0.8,
             linetype = 2,
             color = 'gray30') +
  geom_smooth(linetype = 1,
              size = 1,
              se = FALSE) +
  geom_vline(xintercept = min(filter(power_results, power >= 0.8)$power),
             linetype = 2) +
  scale_x_continuous("Sample Size", breaks = seq(0, 2000, 200)) + scale_y_continuous("Power", breaks = seq(0, 1, .2)) +
  theme_bw(base_size = 14) 
```

```{r}
ggplot(power_results_cr, aes(x = sample_size, y = power)) +
  geom_point(size = 1.5, color = 'gray40') +
  geom_hline(yintercept = 0.8,
             linetype = 2,
             color = 'gray30') +
  geom_smooth(linetype = 1,
              size = 1,
              se = FALSE) +
  geom_vline(xintercept = min(filter(power_results, power >= 0.8)$power),
             linetype = 2) +
  scale_x_continuous("Sample Size", breaks = seq(0, 2000, 200)) + scale_y_continuous("Power", breaks = seq(0, 1, .2)) +
  theme_bw(base_size = 14) 
```

```{r}
ggplot(power_results_fc, aes(x = sample_size, y = power)) +
  geom_point(size = 1.5, color = 'gray40') +
  geom_hline(yintercept = 0.8,
             linetype = 2,
             color = 'gray30') +
  geom_smooth(linetype = 1,
              size = 1,
              se = FALSE) +
  geom_vline(xintercept = min(filter(power_results, power >= 0.8)$power),
             linetype = 2) +
  scale_x_continuous("Sample Size", breaks = seq(0, 2000, 200)) + scale_y_continuous("Power", breaks = seq(0, 1, .2)) +
  theme_bw(base_size = 14) 
```

