---
title: "CAR MemMatch Analysis"
author: "Meg McMahon"
date: "10/26/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(reshape2)
library(magrittr)
library(broom)
library(knitr)
library(RColorBrewer)
library(ggcorrplot)

load("data/merged_data.RData")
tst <- readxl::read_xlsx("/Users/megmcmahon/Box/CogNeuroLab/Aging Decision Making R01/Data/Actigraphy Data/Average Sleep Time.xlsx")
d <- merge(d, tst, by = "record_id")

```


# Data Cleaning
```{r data cleaning}

d$sex[substr(d$sex, 0, 1) == "f" | substr(d$sex, 0, 1) == "F"] <- "F"
d$sex[substr(d$sex, 0, 1) == "m" | substr(d$sex, 0, 1) == "M"] <- "M"
d$sex <- factor(d$sex)


d$edu <- substr(d$edu, 0, 2)
d$edu <- str_pad(d$edu, 2, pad = "0")
d$edu <- as.numeric(d$edu)

d$accuracy[d$accuracy < 0.55] <- NA

sum(is.na(d$accuracy))
d$group[is.na(d$accuracy)]


```

# Demographics
```{r demographics}
d %>%
  group_by(group) %>%
  summarize(N = n(), 
            age_mean = mean(age), age_sd = sd(age), 
            Female = sum(sex == "F"), Male = sum(sex == "M"),
            years_edu = mean(edu), edu_sd = sd(edu))
```


# Accuracy and Reaction Time Barplots
```{r}

d2 <- select(d, group, IS:fnlrgact, mean_sleeptime,
             accuracy, rt, age)
d2 <- select(d2, -M10_start_diff, -L5_start_diff, -M10_starttime, -L5_starttime)
d2 <- na.omit(d2)

d2.mlt <- melt(d2, id.vars=c("group", "accuracy", "rt"))

d2.mlt %>%
  ggplot(aes(x = group, y = value, # set x, y coordinates
             color = group)) +    # color by treatment
  geom_boxplot() +
  facet_wrap(~variable, scales = "free_y") + 
  theme_classic() +
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8])
  
#Accuracy by group
d2.mlt%>%  
  ggplot(aes(x = group, y = accuracy, color = group)) +
  geom_boxplot() + 
  theme_classic() + 
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8])

#Reaction time by group
d2.mlt%>%  
  ggplot(aes(x = group, y = rt, color = group)) +
  geom_boxplot() + 
  theme_classic() + 
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8])


```


```{r}
d2 <- select(d, group, IS:fnlrgact, mean_sleeptime, 
             accuracy, rt, age, fo_match_RT_C,fo_mismatch_RT_C,
             so_match_RT_C,so_mismatch_RT_C,fo_match_accuracy,fo_mismatch_accuracy,
             so_match_accuracy,so_mismatch_accuracy,-M10_start_diff,
             -L5_start_diff,-M10_starttime, -L5_starttime)

d2[,2:length(d2)] <- sapply(d2[,2:length(d2)],as.numeric)
d2 <- d2[complete.cases(d2),]

nOA <- sum(d2$group == "OA")
nYA <- sum(d2$group == "YA")

d2_YA <- subset(d2, d2$group == "YA")
d2_OA <- subset(d2, d2$group == "OA")
d2[c("group")] <- list(NULL); d2_OA[c("group")] <- list(NULL); d2_YA[c("group")] <- list(NULL)

d2_cor <- cor(d2, method = "pearson")
d2_cor_OA <- cor(d2_OA, method = "pearson")
d2_cor_YA <- cor(d2_YA, method = "pearson")

ggcorrplot(d2_cor, p.mat = cor_pmat(d2), colors = c("red", "white", "orange"), ggtheme = ggplot2::theme_minimal, hc.order = FALSE, insig = 'blank')

ggcorrplot(d2_cor_OA, p.mat = cor_pmat(d2_OA), colors = c("red", "white", "orange"), ggtheme = ggplot2::theme_minimal, hc.order = FALSE, insig = 'blank')

ggcorrplot(d2_cor_YA, p.mat = cor_pmat(d2_YA), colors = c("red", "white", "orange"), ggtheme = ggplot2::theme_minimal, hc.order = FALSE, insig = 'blank')
```


# CAR vs MemMatch Task Accuracy
```{r plot accuracy by CAR}



d2 <- select(d, group, IS:fnlrgact, mean_sleeptime,
             accuracy, rt, age)
d2 <- select(d2, -M10_start_diff, -L5_start_diff, -M10_starttime, -L5_starttime)
d2 <- na.omit(d2)

d2.mlt <- melt(d2, id.vars=c("group", "accuracy", "rt"))

d2.mlt %>%
  ggplot(aes(x=value, y=accuracy)) + 
  geom_point(aes(color=group)) + 
  geom_smooth(method="lm", na.rm = TRUE, se = FALSE, color = "black") +
  facet_wrap(~ variable, scales = "free_x") +
  theme_classic() +
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8]) +
  theme(axis.text.y = element_blank(), axis.text.x = element_blank())


```



```{r accuracy multiple simple regression}

d2 %>% 
  dplyr::select(-accuracy) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$accuracy ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map_dbl("r.squared") %>% 
  tidy %>%
  dplyr::arrange(desc(x)) %>%
  rename(r.squared = x) -> r2s

ggplot(r2s, aes(x = reorder(names, r.squared), y = r.squared)) + 
  geom_point(size = 5, color = "red") +
  ylab(expression(R^{2})) +
  xlab("predictors") +
  ggtitle("Explained variance per predictor from simple regressions")


d2 %>% 
  dplyr::select(-accuracy) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$accuracy ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map(c("coefficients")) %>% 
  map_dbl(8)  %>% # 8th element is the p-value 
  tidy %>% 
  dplyr::arrange(x) %>% 
  rename(p.value = x) -> ps


kable(merge(r2s, ps, by = "names", sort = FALSE), digits = 4, caption = "Accuracy")

```


# CAR vs MemMatch Task Reaction Time

```{r plot reaction time by CAR}
d2.mlt %>%
  ggplot(aes(x=value, y=rt)) + 
  geom_point(aes(color=group)) + 
  geom_smooth(method="lm", na.rm = TRUE, se = FALSE, color = "black") +
  facet_wrap(~ variable, scales = "free_x", ncol = 4) +
  theme_classic() +
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8]) +
  theme(axis.text.y = element_blank(), axis.text.x = element_blank())
```


```{r reaction time multiple simple regression}



d2 %>% 
  dplyr::select(-rt) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$rt ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map_dbl("r.squared") %>% 
  tidy %>%
  dplyr::arrange(desc(x)) %>%
  rename(r.squared = x) -> r2s

ggplot(r2s, aes(x = reorder(names, r.squared), y = r.squared)) + 
  geom_point(size = 5, color = "red") +
  ylab(expression(R^{2})) +
  xlab("predictors") +
  ggtitle("Explained variance per predictor from simple regressions")

d2 %>% 
  dplyr::select(-rt) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$rt ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map(c("coefficients")) %>% 
  map_dbl(8)  %>% # 8th element is the p-value 
  tidy %>% 
  dplyr::arrange(x) %>% 
  rename(p.value = x) -> ps

kable(merge(r2s, ps, by = "names", sort = FALSE), digits = 4, caption = "Reaction Time")

```



# MemMatch Task Accuracy by Match vs. Mismatch Trial

```{r}

d2 <- select(d, group, IS:fnlrgact, mean_sleeptime,
             match_accuracy, mismatch_accuracy)
d2 <- select(d2, -M10_start_diff, -L5_start_diff, -M10_starttime, -L5_starttime)
d2 <- na.omit(d2)

d2.mlt <- melt(d2, id.vars=c("group", "match_accuracy", "mismatch_accuracy"))

#Accuracy on match trials by group
d2.mlt%>%  
  ggplot(aes(x = group, y = match_accuracy, color = group)) +
  geom_boxplot() + 
  theme_classic() + 
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8])

#Accuracy on mismatch trials by group
d2.mlt%>%  
  ggplot(aes(x = group, y = mismatch_accuracy, color = group)) +
  geom_boxplot() + 
  theme_classic() + 
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8])
```



```{r match vs mismatch trials}

d2.mlt %>%
  ggplot(aes(x=value, y=match_accuracy)) + 
  geom_point(aes(color=group)) + 
  geom_smooth(method="lm", na.rm = TRUE, se = FALSE, color = "black") +
  facet_wrap(~ variable, scales = "free_x") +
  theme_classic() +
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8]) +
  theme(axis.text.y = element_blank(), axis.text.x = element_blank())

d2.mlt %>%
  ggplot(aes(x=value, y=mismatch_accuracy)) + 
  geom_point(aes(color=group)) + 
  geom_smooth(method="lm", na.rm = TRUE, se = FALSE, color = "black") +
  facet_wrap(~ variable, scales = "free_x", ncol = 4) +
  theme_classic() +
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8]) +
  theme(axis.text.y = element_blank(), axis.text.x = element_blank())

d2 %>% 
  dplyr::select(-match_accuracy) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$match_accuracy ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map_dbl("r.squared") %>% 
  tidy %>%
  dplyr::arrange(desc(x)) %>%
  rename(r.squared = x) -> r2s



ggplot(r2s, aes(x = reorder(names, r.squared), y = r.squared)) + 
  geom_point(size = 5, color = "red") +
  ylab(expression(R^{2})) +
  xlab("predictors") +
  ggtitle("Explained variance per predictor from simple regressions")

d2 %>% 
  dplyr::select(-match_accuracy) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$match_accuracy ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map(c("coefficients")) %>% 
  map_dbl(8)  %>% # 8th element is the p-value 
  tidy %>% 
  dplyr::arrange(x) %>% 
  rename(p.value = x) -> ps


kable(merge(r2s, ps, by = "names", sort = FALSE), digits = 4, caption = "Match Accuracy")


d2 %>% 
  dplyr::select(-mismatch_accuracy) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$mismatch_accuracy ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map_dbl("r.squared") %>% 
  tidy %>%
  dplyr::arrange(desc(x)) %>%
  rename(r.squared = x) -> r2s



ggplot(r2s, aes(x = reorder(names, r.squared), y = r.squared)) + 
  geom_point(size = 5, color = "red") +
  ylab(expression(R^{2})) +
  xlab("predictors") +
  ggtitle("Explained variance per predictor from simple regressions")

d2 %>% 
  dplyr::select(-mismatch_accuracy) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$mismatch_accuracy ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map(c("coefficients")) %>% 
  map_dbl(8)  %>% # 8th element is the p-value 
  tidy %>% 
  dplyr::arrange(x) %>% 
  rename(p.value = x) -> ps


kable(merge(r2s, ps, by = "names", sort = FALSE), digits = 4, caption = "Mismatch Accuracy")

```


# MemMatch Task Reaction Time by Match vs. Mismatch Trial

```{r}
d2 <- select(d, group, IS:fnlrgact, mean_sleeptime,
             match_RT_C, mismatch_RT_C)
d2 <- select(d2, -M10_start_diff, -L5_start_diff, -M10_starttime, -L5_starttime)
d2 <- na.omit(d2)

d2.mlt <- melt(d2, id.vars=c("group", "match_RT_C", "mismatch_RT_C"))

# Reaction time on match trials by group
d2.mlt%>%  
  ggplot(aes(x = group, y = match_RT_C, color = group)) +
  geom_boxplot() + 
  theme_classic() + 
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8])

# Reaction time on mismatch trials by group
d2.mlt%>%  
  ggplot(aes(x = group, y = mismatch_RT_C, color = group)) +
  geom_boxplot() + 
  theme_classic() + 
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8])
```



```{r match vs. mismatch reaction time}

d2.mlt %>%
  ggplot(aes(x=value, y=match_RT_C)) + 
  geom_point(aes(color=group)) + 
  geom_smooth(method="lm", na.rm = TRUE, se = FALSE, color = "black") +
  facet_wrap(~ variable, scales = "free_x") +
  theme_classic() +
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8]) +
  theme(axis.text.y = element_blank(), axis.text.x = element_blank())

d2.mlt %>%
  ggplot(aes(x=value, y=mismatch_RT_C)) + 
  geom_point(aes(color=group)) + 
  geom_smooth(method="lm", na.rm = TRUE, se = FALSE, color = "black") +
  facet_wrap(~ variable, scales = "free_x", ncol = 4) +
  theme_classic() +
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8]) +
  theme(axis.text.y = element_blank(), axis.text.x = element_blank())

d2 %>% 
  dplyr::select(-match_RT_C) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$match_RT_C ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map_dbl("r.squared") %>% 
  tidy %>%
  dplyr::arrange(desc(x)) %>%
  rename(r.squared = x) -> r2s



ggplot(r2s, aes(x = reorder(names, r.squared), y = r.squared)) + 
  geom_point(size = 5, color = "red") +
  ylab(expression(R^{2})) +
  xlab("predictors") +
  ggtitle("Explained variance per predictor from simple regressions")

d2 %>% 
  dplyr::select(-match_RT_C) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$match_RT_C ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map(c("coefficients")) %>% 
  map_dbl(8)  %>% # 8th element is the p-value 
  tidy %>% 
  dplyr::arrange(x) %>% 
  rename(p.value = x) -> ps


kable(merge(r2s, ps, by = "names", sort = FALSE), digits = 4, caption = "Match Reaction Time")


d2 %>% 
  dplyr::select(-mismatch_RT_C) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$mismatch_RT_C ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map_dbl("r.squared") %>% 
  tidy %>%
  dplyr::arrange(desc(x)) %>%
  rename(r.squared = x) -> r2s



ggplot(r2s, aes(x = reorder(names, r.squared), y = r.squared)) + 
  geom_point(size = 5, color = "red") +
  ylab(expression(R^{2})) +
  xlab("predictors") +
  ggtitle("Explained variance per predictor from simple regressions")

d2 %>% 
  dplyr::select(-mismatch_RT_C) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$mismatch_RT_C ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map(c("coefficients")) %>% 
  map_dbl(8)  %>% # 8th element is the p-value 
  tidy %>% 
  dplyr::arrange(x) %>% 
  rename(p.value = x) -> ps


kable(merge(r2s, ps, by = "names", sort = FALSE), digits = 4, caption = "Mismatch Reaction Time")

```


# MemMatch Task Accuracy by Face vs. Scene Trial

```{r face vs scene stimulus accuracy}

d2 <- select(d, group, IS:fnlrgact, mean_sleeptime,
             fo_match_accuracy, fo_mismatch_accuracy,
             so_match_accuracy, so_mismatch_accuracy)

d2 <- na.omit(d2)

d2 <- d2 %>%
  as_tibble() %>%
  mutate(fo_accuracy = (fo_match_accuracy+fo_mismatch_accuracy)/2,
         so_accuracy = (so_match_accuracy+so_mismatch_accuracy)/2,
         fo_match_accuracy = NULL,
         fo_mismatch_accuracy = NULL,
         so_match_accuracy = NULL, 
         so_mismatch_accuracy = NULL,
         M10_start_diff = NULL,
         L5_start_diff = NULL,
         M10_starttime = NULL, 
         l5_starttime = NULL)

d2.mlt <- melt(d2, id.vars=c("group", "fo_accuracy", "so_accuracy"))

# Accuracy on match trials by group
d2.mlt%>%  
  ggplot(aes(x = group, y = fo_accuracy, color = group)) +
  geom_boxplot() + 
  theme_classic() + 
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8])

# Accuracy on mismatch trials by group
d2.mlt%>%  
  ggplot(aes(x = group, y = so_accuracy, color = group)) +
  geom_boxplot() + 
  theme_classic() + 
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8])

```


```{r}
d2.mlt %>%
  ggplot(aes(x=value, y=fo_accuracy)) + 
  geom_point(aes(color=group)) +
  geom_smooth(method="lm", na.rm = TRUE, se = FALSE, color = "black") +
  facet_wrap(~ variable, scales = "free_x", ncol = 4) +
  theme_classic() +
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8]) +
  theme(axis.text.y = element_blank(), axis.text.x = element_blank())

d2.mlt %>%
  ggplot(aes(x=value, y=so_accuracy)) + 
  geom_point(aes(color=group)) + 
  geom_smooth(method="lm", na.rm = TRUE, se = FALSE, color = "black") +
  facet_wrap(~ variable, scales = "free_x", ncol = 4) +
  theme_classic() +
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8]) +
  theme(axis.text.y = element_blank(), axis.text.x = element_blank())


d2 %>% 
  dplyr::select(-fo_accuracy) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$fo_accuracy ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map_dbl("r.squared") %>% 
  tidy %>%
  dplyr::arrange(desc(x)) %>%
  rename(r.squared = x) -> r2s



ggplot(r2s, aes(x = reorder(names, r.squared), y = r.squared)) + 
  geom_point(size = 5, color = "red") +
  ylab(expression(R^{2})) +
  xlab("predictors") +
  ggtitle("Explained variance per predictor from simple regressions")

d2 %>% 
  dplyr::select(-fo_accuracy) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$fo_accuracy ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map(c("coefficients")) %>% 
  map_dbl(8)  %>% # 8th element is the p-value 
  tidy %>% 
  dplyr::arrange(x) %>% 
  rename(p.value = x) -> ps


kable(merge(r2s, ps, by = "names", sort = FALSE), digits = 4, caption = "Face-Object Accuracy")


d2 %>% 
  dplyr::select(-so_accuracy) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$so_accuracy ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map_dbl("r.squared") %>% 
  tidy %>%
  dplyr::arrange(desc(x)) %>%
  rename(r.squared = x) -> r2s



ggplot(r2s, aes(x = reorder(names, r.squared), y = r.squared)) + 
  geom_point(size = 5, color = "red") +
  ylab(expression(R^{2})) +
  xlab("predictors") +
  ggtitle("Explained variance per predictor from simple regressions")

d2 %>% 
  dplyr::select(-so_accuracy) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$so_accuracy ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map(c("coefficients")) %>% 
  map_dbl(8)  %>% # 8th element is the p-value 
  tidy %>% 
  dplyr::arrange(x) %>% 
  rename(p.value = x) -> ps


kable(merge(r2s, ps, by = "names", sort = FALSE), digits = 4, caption = "Scene-Object Accuracy")
```


# MemMatch Task Reaction Time by Face vs. Scene Trial


```{r}

d2 <- select(d, group, IS:fnlrgact, mean_sleeptime,
             fo_match_RT_C, fo_mismatch_RT_C,
             so_match_RT_C, so_mismatch_RT_C)
d2 <- na.omit(d2)

d2 <- d2 %>%
  as_tibble() %>%
  mutate(fo_RT = (fo_match_RT_C+fo_mismatch_RT_C)/2,
         so_RT = (so_match_RT_C+so_mismatch_RT_C)/2,
         fo_match_accuracy = NULL,
         fo_mismatch_accuracy = NULL,
         so_match_accuracy = NULL, 
         so_mismatch_accuracy = NULL,
         M10_start_diff = NULL,
         L5_start_diff = NULL,
         M10_starttime = NULL, 
         L5_starttime = NULL) 

d2.mlt <- melt(d2, id.vars=c("group", "fo_RT", "so_RT"))


# Accuracy on match trials by group
d2.mlt%>%  
  ggplot(aes(x = group, y = fo_RT, color = group)) +
  geom_boxplot() + 
  theme_classic() + 
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8])

# Accuracy on mismatch trials by group
d2.mlt%>%  
  ggplot(aes(x = group, y = so_RT, color = group)) +
  geom_boxplot() + 
  theme_classic() + 
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8])
```


```{r face vs scene reaction time}

d2.mlt %>%
  ggplot(aes(x=value, y=fo_RT)) + 
  geom_point(aes(color=group)) + 
  geom_smooth(method="lm", na.rm = TRUE, se = FALSE, color = "black") +
  facet_wrap(~ variable, scales = "free_x", ncol = 4) +
  theme_classic() +
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8]) +
  theme(axis.text.y = element_blank(), axis.text.x = element_blank())

d2.mlt %>%
  ggplot(aes(x=value, y=so_RT)) + 
  geom_point(aes(color=group)) + 
  geom_smooth(method="lm", na.rm = TRUE, se = FALSE, color = "black") +
  facet_wrap(~ variable, scales = "free_x", ncol = 4) +
  theme_classic() +
  scale_colour_manual(values = brewer.pal(8, "Paired")[7:8]) +
  theme(axis.text.y = element_blank(), axis.text.x = element_blank())


d2 %>% 
  dplyr::select(-fo_RT) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$fo_RT ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map_dbl("r.squared") %>% 
  tidy %>%
  dplyr::arrange(desc(x)) %>%
  rename(r.squared = x) -> r2s



ggplot(r2s, aes(x = reorder(names, r.squared), y = r.squared)) + 
  geom_point(size = 5, color = "red") +
  ylab(expression(R^{2})) +
  xlab("predictors") +
  ggtitle("Explained variance per predictor from simple regressions")

d2 %>% 
  dplyr::select(-fo_RT) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$fo_RT ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map(c("coefficients")) %>% 
  map_dbl(8)  %>% # 8th element is the p-value 
  tidy %>% 
  dplyr::arrange(x) %>% 
  rename(p.value = x) -> ps


kable(merge(r2s, ps, by = "names", sort = FALSE), digits = 4, caption = "Face-Object Reaction Time")


d2 %>% 
  dplyr::select(-so_RT) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$so_RT ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map_dbl("r.squared") %>% 
  tidy %>%
  dplyr::arrange(desc(x)) %>%
  rename(r.squared = x) -> r2s



ggplot(r2s, aes(x = reorder(names, r.squared), y = r.squared)) + 
  geom_point(size = 5, color = "red") +
  ylab(expression(R^{2})) +
  xlab("predictors") +
  ggtitle("Explained variance per predictor from simple regressions")

d2 %>% 
  dplyr::select(-so_RT) %>%  # exclude outcome, leave only predictors 
  map(~lm(d2$so_RT ~ .x, data = d2)) %>% 
  map(summary) %>% 
  map(c("coefficients")) %>% 
  map_dbl(8)  %>% # 8th element is the p-value 
  tidy %>% 
  dplyr::arrange(x) %>% 
  rename(p.value = x) -> ps


kable(merge(r2s, ps, by = "names", sort = FALSE), digits = 4, caption = "Scene-Object Reaction Time")
```







