---
title: "CC Volume"
author: "Megan McMahon"
date: "12/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)
library(corrplot)

load("~/Box/CogNeuroLab/Aging Decision Making R01/Data/combined_data_2019-12-13.RData")
d <- select(d, record_id, age, Group, matches("CC_"))
cr <- read_csv("~/Box/CogNeuroLab/Aging Decision Making R01/Data/combined_data_new.csv")
cr <- select(cr, record_id, IS:RA, fact)

d <- merge(d, cr, by = "record_id")
head(d)
```

## Across age groups
```{r}
alpha = 0.05

d1 <- select(d, -record_id, -Group)
d1 <- d1[complete.cases(d1), ]

mat <- cor(d1)
res <- cor.mtest(d1, conf.level = (1-alpha))
corrplot(mat, p.mat = res$p, sig.level = alpha, insig = "blank", type = "upper")
```


## Older adults
```{r}
oa_data <- filter(d, Group == "Older Adults")
d1 <- select(oa_data, -record_id, -Group)
d1 <- d1[complete.cases(d1), ]

mat <- cor(d1)
res <- cor.mtest(d1, conf.level = (1-alpha))
corrplot(mat, p.mat = res$p, sig.level = alpha, insig = "blank", type = "upper")
```

```{r}
cor.test(oa_data$CC_Mid_Anterior, oa_data$fact)
```


## Young Adults
```{r}
ya_data <- filter(d, Group == "Young Adults")
d1 <- select(ya_data, -record_id, -Group)
d1 <- d1[complete.cases(d1), ]

mat <- cor(d1)
res <- cor.mtest(d1, conf.level = (1-alpha))
corrplot(mat, p.mat = res$p, sig.level = alpha, insig = "blank", type = "upper")
```

```{r}
cor.test(ya_data$CC_Central, ya_data$fact)
```

## From correlation plots
```{r}
#within young adults
cor.test(ya_data$CC_Central, ya_data$IS)

#across all subjects
cor.test(d1$CC_Anterior, d1$IV)


summary(lm(CC_Anterior ~ IV, data = d1))
summary(lm(CC_Anterior ~ IV + age, data = oa_data))
summary(lm(CC_Anterior ~ IV + age, data = ya_data))


```

