---
title: "OHBM 2020"
author: "Megan McMahon"
date: "12/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readr)
library(corrplot)
library(reshape2)
library(car)
library(beset)
library(psych)

load("~/Box/CogNeuroLab/Aging Decision Making R01/Data/combined_data_2020-01-13.RData")
d2 <- d
load("~/Box/CogNeuroLab/Aging Decision Making R01/Data/combined_data_2019-12-25.RData")

#save(d, file = "~/Box/CogNeuroLab/Aging Decision Making R01/Data/combined_data_2019-12-25.RData")

#d[d$record_id == 40160, c("actamp", "actbeta", "actphi", "actmin", "actmesor", "actupmesor", "actdownmesor", "actalph", "actwidthratio", "rsqact", "fact", "fnlrgact")] <- NA

ya_data <- d[d$Group == "Young Adults", ]
oa_data <- d[d$Group == "Older Adults", ]

ya_data2 <- d2[d2$Group == "Young Adults", ]
oa_data2 <- d2[d2$Group == "Older Adults", ]
```

## Demographic information -- need to download
```{r}
d %>%
  group_by(Group) %>%
  select(Group, age) %>%
  na.omit(Group) %>%
  summarise_all(mean, na.rm = TRUE)
```


## Rest-activity rhythms and aging
```{r}
d %>%
  group_by(Group) %>%
  select(Group, IS:RA) %>%
  na.omit(Group) %>%
  summarise_all(mean, na.rm = TRUE)
```
```{r}
d2 %>%
  group_by(Group) %>%
  select(Group, IS:RA) %>%
  na.omit(Group) %>%
  summarise_all(mean, na.rm = TRUE)

t.test(IS ~ Group, data = d2)
t.test(IV ~ Group, data = d2)
t.test(RA ~ Group, data = d2)
```


```{r}
d %>%
  group_by(Group) %>%
  select(Group, actquot, actamp:fact) %>%
  na.omit(Group) %>%
  summarise_all(mean, na.rm = TRUE)

t.test(actquot ~ Group, data = d2) #0.05 YA > OA
t.test(actamp ~ Group, data = d2) #NS
t.test(actbeta ~ Group, data = d2) #0.046 YA < OA
t.test(actalph ~ Group, data = d2) #0.057 YA < OA
t.test(actupmesor ~ Group, data = d2) # p < 0.001, YA > OA
t.test(actdownmesor ~ Group, data = d2) #same
t.test(actphi ~ Group, data = d2) #same
t.test(fact ~ Group, data = d2) #NS
```

```{r}
d2 %>%
  group_by(Group) %>%
  select(Group, actquot, actamp:fact) %>%
  na.omit(Group) %>%
  summarise_all(mean, na.rm = TRUE)
```


## Rest-activity rhythms and corpus callosum microstructure

### Older adults
```{r}
#mean diffusivity
#alpha
stepdata <- select(oa_data, record_id, age, actalph:fact, -rsqact, -actwidthratio, md_mean_cc)
sum(complete.cases(stepdata))
mod <- beset_lm(md_mean_cc ~ ., data = stepdata, n_folds = sum(complete.cases(stepdata)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata))) 
summary(lm(md_mean_cc ~ actalph + age, data = oa_data))
#fractional anisotropy
#fact
stepdata <- select(oa_data, age, actalph:fact, -rsqact, -actwidthratio, fa_mean_cc)
mod <- beset_lm(fa_mean_cc ~ ., data = stepdata, n_folds = sum(complete.cases(stepdata)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata))) 
summary(lm(fa_mean_cc ~ actalph + age, data = oa_data))
#volume
#hodgepodge
stepdata <- select(oa_data, age, actalph:fact, -rsqact, -actwidthratio, CC_Total)
mod <- beset_lm(CC_Total ~ ., data = stepdata, n_folds = sum(complete.cases(stepdata)))
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata))) 
summary(lm(CC_Total ~ age + actalph, data = oa_data))
```


```{r}
ggplot() + 
  geom_density(data = oa_data, aes(x = fact, fill = "blue")) + 
  geom_density(data = oa_data2, aes(x = fact, fill = "red"))
```

```{r}
d2 %>%
  filter(Robustness != "NA") %>%
  ggplot() + 
  geom_boxplot(aes(x = Group, y = fact, fill = Group)) +
  scale_fill_manual(values = c("blue", "red")) +
  ylab("Robustness (F-statistic)") + xlab("Age Group")
```


```{r}
d2$record_id[d2$fact == min(d2$fact, na.rm = TRUE)] #40825
d2$record_id[d2$fact == max(d2$fact, na.rm = TRUE)] #40782
```

```{r}
d2 %>%
  filter(Robustness != "NA") %>%
  ggplot() + 
  geom_boxplot(aes(x = Robustness, y = actphi, fill = Robustness)) +
  scale_fill_manual(values = c("blue", "red")) +
  xlab("Robustness (F-statistic)") + ylab("Acrophase (phi)")
```
```{r}
d2 %>%
  filter(Group == "Older Adults") %>%
  select(actamp, actphi, actmesor, actalph, actbeta, fact) %>%
  psych::describe(quant=c(.25,.75)) %>%
  as_tibble(rownames="rowname") %>%
  select(var=rowname, min, max, mean, sd) %>%
  print()
  
```

```{r}
d2 %>%
  filter(Group == "Young Adults") %>%
  select(actamp, actphi, actmesor, actalph, actbeta, fact) %>%
  psych::describe(quant=c(.25,.75)) %>%
  as_tibble(rownames="rowname") %>%
  select(var=rowname, min, max, mean, sd) %>%
  print()

```



```{r}
ggplot() + 
  geom_density(data = oa_data, aes(x = actalph, fill = "blue")) + 
  geom_density(data = oa_data2, aes(x = actalph, fill = "red"))

```

```{r}
ggplot() + 
  geom_density(data = oa_data, aes(x = md_mean_cc, fill = "blue")) + 
  geom_density(data = oa_data2, aes(x = md_mean_cc, fill = "red"))
```

```{r}
ggplot() + 
  geom_density(data = oa_data, aes(x = fa_mean_cc, fill = "blue")) + 
  geom_density(data = oa_data2, aes(x = fa_mean_cc, fill = "red"))

```


```{r}
stepdata2 <- select(oa_data2, record_id, age, actalph:fact, -rsqact, -actwidthratio, md_mean_cc)
sum(complete.cases(stepdata2))
mod_md <- beset_lm(md_mean_cc ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod_md, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2, record_id, age, actalph:fact, -rsqact, -actwidthratio, md_mean_3)
sum(complete.cases(stepdata2))
mod_md2 <- beset_lm(md_mean_3 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod_md2, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2, record_id, age, actalph:fact, -rsqact, -actwidthratio, md_mean_4)
sum(complete.cases(stepdata2))
mod_md2 <- beset_lm(md_mean_4 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod_md2, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2, record_id, age, actalph:fact, -rsqact, -actwidthratio, md_mean_5)
sum(complete.cases(stepdata2))
mod_md2 <- beset_lm(md_mean_5 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod_md2, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

#fractional anisotropy
#fact
stepdata2 <- select(oa_data2, age, actalph:fact, -rsqact, -actwidthratio, fa_mean_cc)
mod_fa <- beset_lm(fa_mean_cc ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod_fa, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) 
#summary(lm(fa_mean_cc ~ actalph + age, data = oa_data2)) NS

stepdata2 <- select(oa_data2, age, actalph:fact, -rsqact, -actwidthratio, fa_mean_3)
mod_fa3 <- beset_lm(fa_mean_3 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod_fa3, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) 
summary(lm(fa_mean_3 ~ actalph * age, data = oa_data2)) #p = 0.0646
summary(lm(fa_mean_3 ~ actalph + age, data = oa_data2)) #p = 0.08 actalph, age NS


stepdata2 <- select(oa_data2, age, actalph:fact, -rsqact, -actwidthratio, fa_mean_4)
mod_fa4 <- beset_lm(fa_mean_4 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod_fa4, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2, age, actalph:fact, -rsqact, -actwidthratio, fa_mean_5)
mod_fa5 <- beset_lm(fa_mean_5 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod_fa5, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) 
summary(lm(fa_mean_5 ~ actalph + age, data = oa_data2)) #p = 0.09 actalph, age NS
summary(lm(fa_mean_5 ~ actalph * age, data = oa_data2)) #p = 0.0757

#volume
stepdata2 <- select(oa_data2, age, actalph:fact, -rsqact, -actwidthratio, CC_Total)
mod <- beset_lm(CC_Total ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)))
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2, age, actalph:fact, -rsqact, -actwidthratio, CC_Anterior)
mod <- beset_lm(CC_Anterior ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)))
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS
```

### Non-parametric variable analysis
```{r}
stepdata2 <- select(oa_data2, age, IS:RA, fa_mean_3)
mod_fa3 <- beset_lm(fa_mean_3 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod_fa3, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2, age, IS:RA, fa_mean_4)
mod_fa4 <- beset_lm(fa_mean_4 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod_fa4, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2, age, IS:RA, fa_mean_5)
mod_fa5 <- beset_lm(fa_mean_5 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod_fa5, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2, age, IS:RA, md_mean_3)
mod_fa3 <- beset_lm(md_mean_3 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod_fa3, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2, age, IS:RA, md_mean_4)
mod_fa4 <- beset_lm(md_mean_4 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod_fa4, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS
summary(lm(md_mean_4 ~ age + RA, data = stepdata2)) #only age sig. predictor

stepdata2 <- select(oa_data2, age, IS:RA, md_mean_5)
mod_fa5 <- beset_lm(md_mean_5 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod_fa5, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS
```

## Cosinor rest-activity measures by robustness
```{r}
t.test(fact ~ Group, data = d) #NS
d$Robustness <- factor(ifelse(d$fact <= median(d$fact, na.rm = TRUE), 0, 1), labels = c("Low", "High"))
d2$Robustness <- factor(ifelse(d2$fact <= median(d2$fact, na.rm = TRUE), 0, 1), labels = c("Low", "High"))

ya_data <- d[d$Group == "Young Adults", ]
oa_data <- d[d$Group == "Older Adults", ]

ya_data2 <- d2[d2$Group == "Young Adults", ]
oa_data2 <- d2[d2$Group == "Older Adults", ]

d2 %>%
  group_by(Group, Robustness) %>%
  summarise(n = n())

d2 %>%
  group_by(Group, Robustness) %>%
  select(Group, actquot, actamp:fact) %>%
  na.omit(Group) %>%
  summarise_all(mean, na.rm = TRUE)
```


### Are results different for older adults with good model fit vs. poor model fit?
```{r}
#mean diffusivity
#alpha
stepdata2 <- select(oa_data2[oa_data2$Robustness == "High",], record_id, age, actalph:fact, -rsqact, -actwidthratio, md_mean_cc)
sum(complete.cases(stepdata))
mod <- beset_lm(md_mean_cc ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) 
summary(lm(md_mean_cc ~ actalph + age, data = stepdata2)) #age sig, actalph sig, model p = 0.009

stepdata2 <- select(oa_data2[oa_data2$Robustness == "High",], age, actalph:fact, -rsqact, -actwidthratio, md_mean_3)
sum(complete.cases(stepdata))
mod <- beset_lm(md_mean_3 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) 
summary(lm(md_mean_3 ~ actalph + age, data = stepdata2)) #alpha p = 0.008, age NS, model p = 0.01

stepdata2 <- select(oa_data2[oa_data2$Robustness == "High",], age, actalph:fact, -rsqact, -actwidthratio, md_mean_4)
sum(complete.cases(stepdata))
mod <- beset_lm(md_mean_4 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) 
summary(lm(md_mean_4 ~ actalph + age, data = stepdata2)) # age and alpha significant, model p = 0.018

stepdata2 <- select(oa_data2[oa_data2$Robustness == "High",], age, actalph:fact, -rsqact, -actwidthratio, md_mean_5)
sum(complete.cases(stepdata))
mod <- beset_lm(md_mean_5 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) 
summary(lm(md_mean_5 ~ actalph + age, data = stepdata2)) # model p = 0.03, weak pred age and actalph p < 0.1

#fractional anisotropy
#fact
stepdata2 <- select(oa_data2[oa_data2$Robustness == "High",], age, actalph:fact, -rsqact, -actwidthratio, fa_mean_cc)
mod <- beset_lm(fa_mean_cc ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) 
summary(lm(fa_mean_cc ~ actalph + age, data = stepdata2)) #NS

stepdata2 <- select(oa_data2[oa_data2$Robustness == "High",], age, actalph:fact, -rsqact, -actwidthratio, fa_mean_3)
mod <- beset_lm(fa_mean_3 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2[oa_data2$Robustness == "High",], age, actalph:fact, -rsqact, -actwidthratio, fa_mean_4)
mod <- beset_lm(fa_mean_4 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2[oa_data2$Robustness == "High",], age, actalph:fact, -rsqact, -actwidthratio, fa_mean_5)
mod <- beset_lm(fa_mean_5 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

#volume
#hodgepodge
stepdata2 <- select(oa_data2[oa_data2$Robustness == "High",], age, actalph:fact, -rsqact, -actwidthratio, CC_Total)
mod <- beset_lm(CC_Total ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)))
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) 
summary(lm(CC_Total ~ age + actalph, data = stepdata2)) #NS
summary(lm(CC_Total ~ age + fact, data = oa_data2)) #NS

stepdata2 <- select(oa_data2[oa_data2$Robustness == "High",], age, actalph:fact, -rsqact, -actwidthratio, CC_Anterior)
mod <- beset_lm(CC_Anterior ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)))
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS
summary(lm(CC_Anterior ~ age + actalph, data = stepdata2)) #NS
summary(lm(CC_Anterior ~ age + fact, data = oa_data2)) #NS
```
```{r}
#mean diffusivity
#genu - fact relationship in older adults with low fact
stepdata2 <- select(oa_data2[oa_data2$Robustness == "Low",], record_id, age, actalph:fact, -rsqact, -actwidthratio, md_mean_cc)
sum(complete.cases(stepdata))
mod <- beset_lm(md_mean_cc ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2[oa_data2$Robustness == "Low",], age, actalph:fact, -rsqact, -actwidthratio, md_mean_3)
sum(complete.cases(stepdata))
mod <- beset_lm(md_mean_3 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #fact

stepdata2 <- select(oa_data2[oa_data2$Robustness == "Low",], age, actalph:fact, -rsqact, -actwidthratio, md_mean_4)
sum(complete.cases(stepdata))
mod <- beset_lm(md_mean_4 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2[oa_data2$Robustness == "Low",], age, actalph:fact, -rsqact, -actwidthratio, md_mean_5)
sum(complete.cases(stepdata))
mod <- beset_lm(md_mean_5 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

#####question - how do different na rm options affect analysis?

#fractional anisotropy
#fact
stepdata2 <- select(oa_data2[oa_data2$Robustness == "Low",], age, actalph:fact, -rsqact, -actwidthratio, fa_mean_cc)
mod <- beset_lm(fa_mean_cc ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2[oa_data2$Robustness == "Low",], age, actalph:fact, -rsqact, -actwidthratio, fa_mean_3)
mod <- beset_lm(fa_mean_3 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2[oa_data2$Robustness == "Low",], age, actalph:fact, -rsqact, -actwidthratio, fa_mean_4)
mod <- beset_lm(fa_mean_4 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

stepdata2 <- select(oa_data2[oa_data2$Robustness == "Low",], age, actalph:fact, -rsqact, -actwidthratio, fa_mean_5)
mod <- beset_lm(fa_mean_5 ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)), force_in = "age")
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS

#volume
stepdata2 <- select(oa_data2[oa_data2$Robustness == "Low",], age, actalph:fact, -rsqact, -actwidthratio, CC_Total)
mod <- beset_lm(CC_Total ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)))
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #actalph only sig predictor
summary(lm(CC_Total ~ age * actalph, data = stepdata2)) #B < 0 

stepdata2 <- select(oa_data2[oa_data2$Robustness == "Low",], age, actalph:fact, -rsqact, -actwidthratio, CC_Anterior)
mod <- beset_lm(CC_Anterior ~ ., data = stepdata2, n_folds = sum(complete.cases(stepdata2)))
summary(mod, oneSE = FALSE, n_folds = sum(complete.cases(stepdata2))) #NS
summary(lm(CC_Anterior ~ age + actalph, data = stepdata2)) #age weak pred, actalph p = 0.032, model p = 0.02771
```

```{r}
oa_data2 %>%
  select(record_id, matches("md_mean"), actalph, Robustness, -md_mean_sca) %>%
  na.omit(actalph) %>%
  melt(id.vars = c("record_id", "Robustness", "actalph")) %>%
  ggplot(aes(group = Robustness, color = Robustness)) +
  geom_point(aes(x = actalph, y = value, group = Robustness, color = Robustness)) +
  stat_smooth(aes(x = actalph, y = value, group = Robustness, color= Robustness), method = "lm") +
  theme_classic() +
  facet_wrap(. ~ variable, scales = "fixed") +
  #scale_color_manual(values = c("blue", "red")) +
  xlab("Width (alpha)") + ylab("CC Mean Diffusivity") + xlim(-1,-.15)
```

```{r}
oa_data2 %>%
  select(record_id, matches("CC_"), actalph, Robustness, -matches("acc_")) %>%
  na.omit(actalph) %>%
  melt(id.vars = c("record_id", "Robustness", "actalph")) %>%
  ggplot(aes(group = Robustness, color = Robustness)) +
  geom_point(aes(x = actalph, y = value, group = Robustness, color = Robustness)) +
  stat_smooth(aes(x = actalph, y = value, group = Robustness, color= Robustness), method = "lm") +
  theme_classic() +
  facet_wrap(. ~ variable, scales = "free_y") +
  #scale_color_manual(values = c("blue", "red")) +
  xlab("Width (alpha)") + ylab("Volume") + xlim(-1,-.15)

summary(lm(CC_Total ~ actalph^2 + actalph, data = oa_data2))
summary(lm(CC_Total ~ actalph^3 + actalph, data = oa_data2))
summary(lm(CC_Total ~ actalph^4 + actalph, data = oa_data2))

summary(lm(CC_Total ~ fact^2 + fact, data = oa_data2))
summary(lm(CC_Total ~ fact^3 + fact, data = oa_data2))
summary(lm(CC_Total ~ fact^4 + fact, data = oa_data2))

```


### Young adults
```{r}
#mean diffusivity
#alpha
stepdata <- select(ya_data, age, actalph:fact, -rsqact, -actwidthratio, md_mean_cc)
mod <- beset_lm(md_mean_cc ~ ., data = stepdata, n_folds = 29)
summary(mod, oneSE = FALSE, n_folds = 29) 
summary(lm(md_mean_cc ~ actalph, data = ya_data))
#fractional anisotropy
#fact
stepdata <- select(ya_data, age, actalph:fact, -rsqact, -actwidthratio, fa_mean_cc)
mod <- beset_lm(fa_mean_cc ~ ., data = stepdata, n_folds = 29)
summary(mod, oneSE = FALSE, n_folds = 29) 
summary(lm(fa_mean_cc ~ fact, data = ya_data))
#volume
#hodgepodge
stepdata <- select(ya_data, age, actalph:fact, -rsqact, -actwidthratio, CC_Total)
mod <- beset_lm(CC_Total ~ ., data = stepdata, n_folds = 29)
summary(mod, oneSE = FALSE, n_folds = 29) 
summary(lm(CC_Total ~ IS + IV + actalph + fact, data = ya_data))
```



```{r}
d2 <- d

#both - different width effects on md
d2 %>%
  subset(!is.na(actalph)) %>%
  ggplot(aes(group = Group, color = Group)) +
  geom_point(aes(x = actalph, y = md_mean_cc, group = Group, color = Group)) +
  stat_smooth(aes(x = actalph, y = md_mean_cc, group = Group, color= Group), method = "lm") +
  theme_classic() +
  scale_color_manual(values = c("blue", "red")) +
  xlab("Width (alpha)") + ylab("CC Mean Diffusivity") + xlim(-1,-.15) +
  ggsave("~/Box/CogNeuroLab/Aging Decision Making R01/Analysis/ohbm2020/both-alpha-md.png", width = 3, height = 2.5)

#older adults
d2 %>%
  subset(!is.na(actalph)) %>%
  filter(Group == "Older Adults") %>%
  ggplot(aes(group = Group, color = Group)) +
  geom_point(aes(x = actalph, y = md_mean_cc, group = Group, color = Group)) +
  stat_smooth(aes(x = actalph, y = md_mean_cc, group = Group, color= Group), method = "lm") +
  theme_classic() +
  scale_color_manual(values = c("red")) +
  xlab("Width (alpha)") + ylab("CC Mean Diffusivity") + xlim(-1,0) +
  theme(legend.position = "none") +
  ggsave("~/Box/CogNeuroLab/Aging Decision Making R01/Analysis/ohbm2020/oa-alpha-md.png", width = 3, height = 2.5, dpi = 300)

d2 %>%
  subset(!is.na(actalph)) %>%
  filter(Group == "Older Adults") %>%
  ggplot(aes(group = Group, color = Group)) +
  geom_point(aes(x = actalph, y = fa_mean_cc, group = Group, color = Group)) +
  stat_smooth(aes(x = actalph, y = fa_mean_cc, group = Group, color= Group), method = "lm") +
  theme_classic() +
  scale_color_manual(values = c("red")) +
  xlab("Width (alpha)") + ylab("CC Fractional Anisotropy") + xlim(-1,0) +
  theme(legend.position = "none") +
  ggsave("~/Box/CogNeuroLab/Aging Decision Making R01/Analysis/ohbm2020/oa-alpha-fa.png", width = 3, height = 2.5, dpi = 300)

#young adults
d2 %>%
  subset(!is.na(actalph)) %>%
  filter(Group == "Young Adults") %>%
  ggplot(aes(group = Group, color = Group)) +
  geom_point(aes(x = actalph, y = md_mean_cc, group = Group, color = Group)) +
  stat_smooth(aes(x = actalph, y = md_mean_cc, group = Group, color= Group), method = "lm") +
  theme_classic() +
  scale_color_manual(values = c("blue")) +
  xlab("Width (alpha)") + ylab("CC Mean Diffusivity") + xlim(-1,-.15) +
  theme(legend.position = "none") + 
  ggsave("~/Box/CogNeuroLab/Aging Decision Making R01/Analysis/ohbm2020/ya-alpha-md.png", width = 3, height = 2.5, dpi = 300)

d2 %>%
  subset(!is.na(fact)) %>%
  filter(Group == "Young Adults") %>%
  ggplot(aes(group = Group, color = Group)) +
  geom_point(aes(x = fact, y = fa_mean_cc, group = Group, color = Group)) +
  stat_smooth(aes(x = fact, y = fa_mean_cc, group = Group, color= Group), method = "lm") +
  theme_classic() +
  scale_color_manual(values = c("blue")) +
  xlab("Robustness (F-statistic)") + ylab("CC Fractional Anisotropy") + xlim(500,8500) +
  theme(legend.position = "none") +
  ggsave("~/Box/CogNeuroLab/Aging Decision Making R01/Analysis/ohbm2020/ya-fact-fa.png", width = 3, height = 2.5, dpi = 300)
```

```{r}
d2 %>%
  ggplot(aes(group = Group, color = Group)) +
  geom_point(aes(x = age, y = fa_mean_cc, group = Group, color = Group)) +
  stat_smooth(aes(x = age, y = fa_mean_cc, group = Group, color= Group), method = "lm") +
  theme_classic() +
  scale_color_manual(values = c("blue", "red")) +
  xlab("Age") + ylab("CC Fractional Anisotropy") +
  theme(legend.position = "none") 

d2 %>%
  select(Group, fa_mean_3, fa_mean_4, fa_mean_5, age) %>%
  melt(id.vars = c("Group", "age")) %>%
  ggplot(aes(color = Group, group = Group)) +
  geom_point(aes(x = age, y = value, group = Group, color = Group)) +
  stat_smooth(aes(x = age, y = value, group = Group, color= Group), method = "lm") + 
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap(Group ~ variable, scales = "free_x") +
  xlab("Age") + ylab("Fractional Anisotropy") 

d2 %>%
  ggplot(aes(group = Group, color = Group)) +
  geom_point(aes(x = age, y = md_mean_cc, group = Group, color = Group)) +
  stat_smooth(aes(x = age, y = md_mean_cc, group = Group, color= Group), method = "lm") +
  theme_classic() +
  scale_color_manual(values = c("blue", "red")) +
  xlab("Age") + ylab("CC Mean Diffusivity") +
  theme(legend.position = "none") 

d2 %>%
  select(Group, md_mean_3, md_mean_4, md_mean_5, age) %>%
  melt(id.vars = c("Group", "age")) %>%
  ggplot(aes(color = Group, group = Group)) +
  geom_point(aes(x = age, y = value, group = Group, color = Group)) +
  stat_smooth(aes(x = age, y = value, group = Group, color= Group), method = "lm") + 
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap(Group ~ variable, scales = "free_x") +
  xlab("Age") + ylab("Mean Diffusivity") 
```

