library(readr)
library(tidyverse)
library(beset)
library(gridExtra)
library(tableone)
library(corxplor)
library(lm.beta)
library(dplyr)
library(reshape2)
library(rstatix)

work_dir <- "~/Box/CogNeuroLab/Aging Decision Making R01/"
results_dir <- paste0(work_dir, "results/rest-activity_and_white_matter_microstructure/")
figs_dir <- paste0(results_dir, "figures/")
data_dir <- paste0(work_dir, "data/")