---
title: "Circadian Measures and Cognition"
author: "Megan McMahon"
date: "9/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(reshape2)
library(magrittr)
library(broom)
library(knitr)
library(RColorBrewer)
library(ggcorrplot)
```

## R Markdown

```{r load data}
library(readr)

rpx <- read_csv("~/Box/CogNeuroLab/Aging Decision Making R01/Data/Actigraphy/Combined Export File.csv")

efficiency <- aggregate(efficiency ~ subject_id, rpx, mean, na.action = na.omit)
sleep_time <- aggregate(sleep_time ~ subject_id, rpx, mean, na.action = na.omit)
percent_wake <- aggregate(percent_wake ~ subject_id, rpx, mean, na.action = na.omit)
onset_latency <- aggregate(onset_latency ~ subject_id, rpx, mean, na.action = na.omit)
total_ac <- aggregate(total_ac ~ subject_id, rpx, mean, na.action = na.omit)

rpx2 <- merge(efficiency, sleep_time, by = 'subject_id')
rpx2 <- merge(rpx2, percent_wake, by = 'subject_id')
rpx2 <- merge(rpx2, onset_latency, by = 'subject_id')
rpx2 <- merge(rpx2, total_ac, by = 'subject_id')
head(rpx2)

cr <- read_csv('~/Box/CogNeuroLab/Aging Decision Making R01/Data/CR/circadian_rhythms_2019-09-07.csv')
cr$actquot <- cr$actamp/cr$actmesor

neuro <- read_csv('~/Box/CogNeuroLab/Aging Decision Making R01/Data/Neuropsych/AgingDecMemNeuropsyc_DATA_2019-06-12_0708.csv')

bct <- read_csv('~/Box/CogNeuroLab/Aging Decision Making R01/Analysis/bct/bct_x.csv')

d <- merge(cr, neuro, by='record_id', all=TRUE)
d <- merge(d, bct, by='record_id', all=TRUE)
d <- merge(d, rpx2, by.x = 'record_id', by.y = 'subject_id', all=TRUE)
d <- d[(d$age >= 18) & (d$age <= 90) & !is.na(d$age), ]
d$agegroup <- factor(ifelse(d$record_id < 40000, 0, 1))
d$group <- factor(ifelse(d$record_id < 40000, 0, 1), labels = c('Young Adults', 'Older Adults'))

save(d, file = "~/Box/CogNeuroLab/Aging Decision Making R01/Data/combined_data")


dsnmat <- merge(bct, cr, by = 'record_id', all=TRUE)
dsnmat <- dsnmat[!is.na(dsnmat$wb_clustering_x),]
dsnmat <- select(dsnmat, IS:fact)
#write_csv(dsnmat, '~/Box/CogNeuroLab/Aging Decision Making R01/Analysis/cr_dsnmat.csv')
```


```{r circadian measures}
library(formattable)

d %>%
  select(age, IS:fact, group) %>%
  group_by(group) %>%
  summary() 

d %>%
  filter(group == 1) %>%
  select(age, IS:fact) %>%
  summary()

d.mlt <- melt(select(d, record_id, group, IS:actquot, -rsqact, -fnlrgact, -L5_starttime, -M10_starttime), id.vars=c('record_id', 'group'))

ggplot(data = d.mlt, aes(x = variable, y = value, group = group)) + 
  geom_violin(aes(fill = group)) + 
  facet_wrap( ~ variable,  scales='free') + 
  theme_minimal() +
  scale_fill_manual(values = brewer.pal(8, "Paired")[7:8], name = 'Group') +
  xlab(element_blank()) + ylab(element_blank())
```

```{r}
#Effect of age on circadian variables
#Older Adults
summary(lm(actamp ~ age, data = d[d$group == 1,])) #p = 0.0119
summary(lm(fact ~ age, data = d[d$group == 1,])) #p = 0.024507
summary(lm(actupmesor ~ age, data = d[d$group == 1,])) #NS
summary(lm(actdownmesor ~ age, data = d[d$group == 1,])) #NS

summary(lm(RA ~ age, data = d[d$group == 1,])) #NS
summary(lm(IS ~ age, data = d[d$group == 1,])) #NS
summary(lm(IV ~ age, data = d[d$group == 1,])) # p = 0.08

#Younger Adults
summary(lm(actamp ~ age, data = d[d$group == 0,])) #NS
summary(lm(fact ~ age, data = d[d$group == 0,])) #NS
summary(lm(actupmesor ~ age, data = d[d$group == 0,])) #p = 0.0272
summary(lm(actdownmesor ~ age, data = d[d$group == 0,])) #p = 0.0206

summary(lm(RA ~ age, data = d[d$group == 0,])) #NS
summary(lm(IS ~ age, data = d[d$group == 0,])) #NS
summary(lm(IV ~ age, data = d[d$group == 0,])) #NS
```


```{r}
# Stability from day to day
t.test(IS ~ group, data = d) # 0.00142
t.test(IV ~ group, data = d)
t.test(RA ~ group, data = d)
t.test(actamp ~ group, data = d)
t.test(fact ~ group, data = d)

# Morningness preference
t.test(actphi ~ group, data = d) # p = 1.541e-08
t.test(actupmesor ~ group, data = d) # p = 8.015e-05
t.test(actdownmesor~ group, data = d) # p = 4.229e-09

wilcox.test(IS ~ group, data=d) #sig
wilcox.test(IV ~ group, data=d)
wilcox.test(RA ~ group, data=d)
wilcox.test(actamp ~ group, data=d) 
wilcox.test(fact ~ group, data=d) 

wilcox.test(actphi ~ group, data=d) #sig
wilcox.test(actupmesor ~ group, data=d) #sig
wilcox.test(actdownmesor ~ group, data=d) #sig

#Sleep Measures
t.test(sleep_time ~ group, data = d) #NS
t.test(percent_wake ~ group, data = d) #p = 0.03961
t.test(onset_latency ~ group, data = d) #p = 0.0066
t.test(efficiency ~ group, data = d) #NS
```


```{r}

summary(lm(trails_b_z_score ~ gender + IS, data = d)) # NS
summary(lm(ds_backward_score   ~ age + gender + IS, data = d)) # NS
summary(lm(cvlt_ldelay_recall_zscore  ~ IS, data = d)) # p = 0.08899

summary(lm(dmn_participation_x ~ group * RA, data = d))
summary(lm(ds_backward_score   ~ age + gender + RA, data = d))
summary(lm(cvlt_ldelay_recall_zscore  ~ RA, data = d))

summary(lm(trails_b_z_score ~ actupmesor^2 + actupmesor, data = d)) 
summary(lm(ds_backward_score   ~ actupmesor^2 + actupmesor, data = d)) 
summary(lm(cvlt_ldelay_recall_zscore  ~ actupmesor^2 + actupmesor, data = d)) 

summary(lm(trails_b_z_score ~ actamp + group, data = d)) # p = 0.020397
summary(lm(ds_backward_score ~ age + gender + group + actamp, data = d)) # p = 0.0631
summary(lm(cvlt_ldelay_recall_zscore  ~ actamp, data = d)) # NS

summary(lm(trails_b_z_score ~ group + fact, data = d)) # p = 0.015
summary(lm(ds_backward_score   ~ age + gender + fact, data = d)) # NS
summary(lm(cvlt_ldelay_recall_zscore  ~ fact, data = d)) # NS

summary(lm(trails_b_z_score ~ group + actupmesor, data = d)) # p = 0.019
summary(lm(ds_backward_score   ~ age + gender + group + actupmesor, data = d)) # NS
summary(lm(cvlt_ldelay_recall_zscore  ~ actupmesor, data = d)) # NS

summary(lm(trails_b_z_score ~ group + actdownmesor, data = d)) # p = 0.01735
summary(lm(ds_backward_score   ~ age + gender + group + actdownmesor, data = d)) # NS
summary(lm(cvlt_ldelay_recall_zscore  ~ actdownmesor, data = d)) # NS

#No significant relationships between cognition and sleep variables
summary(lm(trails_b_z_score ~ group + sleep_time, data = d))
summary(lm(ds_backward_score   ~ group + sleep_time, data = d)) 
summary(lm(cvlt_ldelay_recall_zscore  ~ sleep_time, data = d))

summary(lm(trails_b_z_score ~ group + percent_wake, data = d)) 
summary(lm(ds_backward_score   ~ group + percent_wake, data = d)) 
summary(lm(cvlt_ldelay_recall_zscore  ~ percent_wake, data = d))

summary(lm(trails_b_z_score ~ group + onset_latency, data = d))
summary(lm(ds_backward_score   ~  group + onset_latency, data = d))
summary(lm(cvlt_ldelay_recall_zscore  ~ onset_latency, data = d))

summary(lm(trails_b_z_score ~ group + efficiency, data = d)) 
summary(lm(ds_backward_score   ~ group + efficiency, data = d)) 
summary(lm(cvlt_ldelay_recall_zscore  ~ efficiency, data = d)) 
```

```{r}

d2.mlt <- melt(select(d, record_id, group, IS:actquot, trails_b_z_score, -rsqact, -fnlrgact, -L5_starttime, -M10_starttime, -actbeta, -actwidthratio), id.vars=c('record_id', 'group', 'trails_b_z_score'))

ggplot(data = d2.mlt) + 
  ggtitle('Circadian Measures and TMT-B Performance') + 
  geom_point(aes(x = value, y = trails_b_z_score, group = group, color = group), size=0.5) + 
  stat_smooth(aes(x = value, y = trails_b_z_score, group = group, color = group), method = 'loess', se = FALSE, fullrange = FALSE) +
  facet_wrap(~ variable,  scales='free') + 
  theme_minimal() +
  scale_color_manual(values = brewer.pal(8, "Paired")[7:8], name = 'Group') +
  xlab(element_blank()) + ylab('TMT-B') +
  theme(axis.text.y = element_blank(), axis.text.x = element_blank())
  
summary(d$actalph)

```



```{r}
lm1 <- lm(trails_b_z_score ~ group + fact, data = d)
par(mfrow=c(2,2))
plot(lm1, which=1:4)

shapiro.test(lm1$residuals) #residuals not normally distributed
```


```{r}
lm2 <- lm(trails_b_z_score ~ group + actupmesor, data = d)
par(mfrow=c(2,2))
plot(lm2, which=1:4)

shapiro.test(lm2$residuals) #residuals not normally distributed
```

```{r correlation plots}
trails_data <- dplyr::select(d, wb_clustering_x:fpn_betweenness_x, contains('trail'))
corrgram::corrgram(trails_data, cor.method = 'spearman', lower.panel=corrgram::panel.fill, upper.panel=corrgram::panel.cor)

ds_data <- dplyr::select(d, wb_clustering_x:fpn_betweenness_x, starts_with('ds'))
corrgram::corrgram(ds_data, cor.method = 'spearman', lower.panel=corrgram::panel.fill,  upper.panel=corrgram::panel.cor)

cvlt_data <- dplyr::select(d, wb_clustering_x:fpn_betweenness_x, contains('cvlt_z'))
corrgram::corrgram(cvlt_data, cor.method = 'spearman', lower.panel=corrgram::panel.fill, upper.panel=corrgram::panel.cor)

cowat_data <- dplyr::select(d, wb_clustering_x:fpn_betweenness_x, contains('cowat'))
corrgram::corrgram(cowat_data, cor.method = 'spearman', lower.panel=corrgram::panel.fill, upper.panel=corrgram::panel.cor)

stroop_data <- dplyr::select(d, wb_clustering_x:fpn_betweenness_x, contains('stroop'))
corrgram::corrgram(stroop_data, cor.method = 'spearman', lower.panel=corrgram::panel.fill, upper.panel=corrgram::panel.cor)

```


```{r bct}
d3.mlt <- melt(select(d, record_id, group, cvlt_ldelay_recall_zscore, wb_clustering_x:fpn_betweenness_x), id.vars=c('record_id', 'group', 'cvlt_ldelay_recall_zscore'))

ggplot(data = d3.mlt) + 
  ggtitle('BCT Metrics and CVLT Long Delay z-score') + 
  geom_point(aes(x = value, y = cvlt_ldelay_recall_zscore, group = group, color = group), size=0.5) + 
  #stat_smooth(aes(x = value, y = ds_backward_score, group = group, color = group), method = 'loess', se = FALSE, fullrange = FALSE) +
  facet_wrap(~ variable,  scales='free') + 
  theme_minimal() +
  scale_color_manual(values = brewer.pal(8, "Paired")[7:8]) +
  xlab(element_blank()) + ylab('CVLT') +
  theme(axis.text.y = element_blank(), axis.text.x = element_blank())


```


```{r}
summary(lm(dmn_modularity_x ~ group * IS, data = d))
summary(lm(dmn_efficiency_x ~ group * IS, data = d))
summary(lm(dmn_clustering_x ~ group * IS, data = d))
summary(lm(dmn_participation_x ~ group * IS, data = d))

summary(lm(dmn_modularity_x ~ group + IS, data = d))
summary(lm(dmn_efficiency_x ~ group + IS, data = d))
summary(lm(dmn_clustering_x ~ group + IS, data = d))
summary(lm(dmn_participation_x ~ group + IS, data = d)) # *
#---------------------------------------------------------

summary(lm(dmn_modularity_x ~ group * IV, data = d))
summary(lm(dmn_efficiency_x ~ group * IV, data = d))
summary(lm(dmn_clustering_x ~ group * IV, data = d))
summary(lm(dmn_participation_x ~ group * IV, data = d))

summary(lm(dmn_modularity_x ~ group + IV, data = d))
summary(lm(dmn_efficiency_x ~ group + IV, data = d)) #
summary(lm(dmn_clustering_x ~ group + IV, data = d)) #
summary(lm(dmn_participation_x ~ group + IV, data = d))

#---------------------------------------------------------

summary(lm(dmn_modularity_x ~ group * RA, data = d))
summary(lm(dmn_efficiency_x ~ group * RA, data = d))
summary(lm(dmn_clustering_x ~ group * RA, data = d))
summary(lm(dmn_participation_x ~ group * RA, data = d)) # **

summary(lm(dmn_modularity_x ~ group + RA, data = d))
summary(lm(dmn_efficiency_x ~ group + RA, data = d))
summary(lm(dmn_clustering_x ~ group + RA, data = d))

#---------------------------------------------------------
summary(lm(dmn_modularity_x ~ group * fact, data = d))
summary(lm(dmn_efficiency_x ~ group * fact, data = d)) # *
summary(lm(dmn_clustering_x ~ group * fact, data = d))
summary(lm(dmn_participation_x ~ group * fact, data = d)) # *

summary(lm(dmn_modularity_x ~ group + fact, data = d))
summary(lm(dmn_clustering_x ~ group + fact, data = d))

#---------------------------------------------------------

summary(lm(dmn_modularity_x ~ group * actamp, data = d))
summary(lm(dmn_efficiency_x ~ group * actamp, data = d))
summary(lm(dmn_clustering_x ~ group * actamp, data = d))
summary(lm(dmn_participation_x ~ group * actamp, data = d)) # 

summary(lm(dmn_modularity_x ~ group + actamp, data = d))
summary(lm(dmn_efficiency_x ~ group + actamp, data = d))
summary(lm(dmn_clustering_x ~ group + actamp, data = d)) # **

#---------------------------------------------------------

summary(lm(dmn_modularity_x ~ group * actphi, data = d))
summary(lm(dmn_efficiency_x ~ group * actphi, data = d))
summary(lm(dmn_clustering_x ~ group * actphi, data = d))
summary(lm(dmn_participation_x ~ group * actphi, data = d))

summary(lm(dmn_modularity_x ~ group + actphi, data = d))
summary(lm(dmn_efficiency_x ~ group + actphi, data = d))
summary(lm(dmn_clustering_x ~ group + actphi, data = d))
summary(lm(dmn_participation_x ~ group + actphi, data = d))

#---------------------------------------------------------
summary(lm(dmn_modularity_x ~ group * sleep_time, data = d))
summary(lm(dmn_efficiency_x ~ group * sleep_time, data = d))
summary(lm(dmn_clustering_x ~ group * sleep_time, data = d))
summary(lm(dmn_participation_x ~ group * sleep_time, data = d))

summary(lm(dmn_modularity_x ~ group + sleep_time, data = d))
summary(lm(dmn_efficiency_x ~ group + sleep_time, data = d))
summary(lm(dmn_clustering_x ~ group + sleep_time, data = d))
summary(lm(dmn_participation_x ~ group + sleep_time, data = d)) # *

#---------------------------------------------------------
summary(lm(dmn_modularity_x ~ group * efficiency, data = d))
summary(lm(dmn_efficiency_x ~ group * efficiency, data = d))
summary(lm(dmn_clustering_x ~ group * efficiency, data = d))
summary(lm(dmn_participation_x ~ group * efficiency, data = d))

summary(lm(dmn_modularity_x ~ group + efficiency, data = d))
summary(lm(dmn_efficiency_x ~ group + efficiency, data = d))
summary(lm(dmn_clustering_x ~ group + efficiency, data = d))
summary(lm(dmn_participation_x ~ group + efficiency, data = d))

#---------------------------------------------------------
summary(lm(dmn_modularity_x ~ group * total_ac, data = d)) #
summary(lm(dmn_efficiency_x ~ group * total_ac, data = d))
summary(lm(dmn_clustering_x ~ group * total_ac, data = d))
summary(lm(dmn_participation_x ~ group * total_ac, data = d))

summary(lm(dmn_modularity_x ~ group + total_ac, data = d))
summary(lm(dmn_efficiency_x ~ group + total_ac, data = d)) #
summary(lm(dmn_clustering_x ~ group + total_ac, data = d)) # *
summary(lm(dmn_participation_x ~ group + total_ac, data = d))
```


```{r}
summary(lm(fpn_modularity_x ~ group * IS, data = d))
summary(lm(fpn_efficiency_x ~ group * IS, data = d))
summary(lm(fpn_clustering_x ~ group * IS, data = d))
summary(lm(fpn_participation_x ~ group * IS, data = d))

summary(lm(fpn_modularity_x ~ group + IS, data = d))
summary(lm(fpn_efficiency_x ~ group + IS, data = d))
summary(lm(fpn_clustering_x ~ group + IS, data = d))
summary(lm(fpn_participation_x ~ group + IS, data = d))

#---------------------------------------------------------

summary(lm(fpn_modularity_x ~ group * IV, data = d))
summary(lm(fpn_efficiency_x ~ group * IV, data = d))
summary(lm(fpn_clustering_x ~ group * IV, data = d))
summary(lm(fpn_participation_x ~ group * IV, data = d))

summary(lm(fpn_modularity_x ~ group + IV, data = d)) # *
summary(lm(fpn_efficiency_x ~ group + IV, data = d)) # **
summary(lm(fpn_clustering_x ~ group + IV, data = d))
summary(lm(fpn_participation_x ~ group + IV, data = d))

#---------------------------------------------------------

summary(lm(fpn_modularity_x ~ group * RA, data = d))
summary(lm(fpn_efficiency_x ~ group * RA, data = d))
summary(lm(fpn_clustering_x ~ group * RA, data = d))
summary(lm(fpn_participation_x ~ group * RA, data = d))

summary(lm(fpn_modularity_x ~ group + RA, data = d))
summary(lm(fpn_efficiency_x ~ group + RA, data = d))
summary(lm(fpn_clustering_x ~ group + RA, data = d)) # **
summary(lm(fpn_participation_x ~ group + RA, data = d))

#---------------------------------------------------------
summary(lm(fpn_modularity_x ~ group * fact, data = d))
summary(lm(fpn_efficiency_x ~ group * fact, data = d))
summary(lm(fpn_clustering_x ~ group * fact, data = d))
summary(lm(fpn_participation_x ~ group * fact, data = d))

summary(lm(fpn_modularity_x ~ group + fact, data = d))
summary(lm(fpn_efficiency_x ~ group + fact, data = d))
summary(lm(fpn_clustering_x ~ group + fact, data = d))
summary(lm(fpn_participation_x ~ group + fact, data = d))

#---------------------------------------------------------

summary(lm(fpn_modularity_x ~ group * actamp, data = d))
summary(lm(fpn_efficiency_x ~ group * actamp, data = d))
summary(lm(fpn_clustering_x ~ group * actamp, data = d))
summary(lm(fpn_participation_x ~ group * actamp, data = d)) # **

summary(lm(fpn_modularity_x ~ group + actamp, data = d))
summary(lm(fpn_efficiency_x ~ group + actamp, data = d))
summary(lm(fpn_clustering_x ~ group + actamp, data = d))

#---------------------------------------------------------

summary(lm(fpn_modularity_x ~ group * actphi, data = d)) # *
summary(lm(fpn_efficiency_x ~ group * actphi, data = d))
summary(lm(fpn_clustering_x ~ group * actphi, data = d)) # *
summary(lm(fpn_participation_x ~ group * actphi, data = d)) # *
summary(lm(fpn_efficiency_x ~ group + actphi, data = d))

summary(lm(fpn_modularity_x ~ group * actupmesor, data = d)) # *
summary(lm(fpn_efficiency_x ~ group * actupmesor, data = d))
summary(lm(fpn_clustering_x ~ group * actupmesor, data = d)) # *
summary(lm(fpn_participation_x ~ group * actupmesor, data = d)) # .
summary(lm(fpn_efficiency_x ~ group + actupmesor, data = d))
summary(lm(fpn_participation_x ~ group + actupmesor, data = d))

#---------------------------------------------------------
summary(lm(fpn_modularity_x ~ group * sleep_time, data = d))
summary(lm(fpn_efficiency_x ~ group * sleep_time, data = d))
summary(lm(fpn_clustering_x ~ group * sleep_time, data = d))
summary(lm(fpn_participation_x ~ group * sleep_time, data = d)) # 

summary(lm(fpn_modularity_x ~ group + sleep_time, data = d))
summary(lm(fpn_efficiency_x ~ group + sleep_time, data = d))
summary(lm(fpn_clustering_x ~ group + sleep_time, data = d))

#---------------------------------------------------------
summary(lm(fpn_modularity_x ~ group * efficiency, data = d))
summary(lm(fpn_efficiency_x ~ group * efficiency, data = d))
summary(lm(fpn_clustering_x ~ group * efficiency, data = d)) # 
summary(lm(fpn_participation_x ~ group * efficiency, data = d))

summary(lm(fpn_modularity_x ~ group + efficiency, data = d))
summary(lm(fpn_efficiency_x ~ group + efficiency, data = d))
summary(lm(fpn_participation_x ~ group + efficiency, data = d))

#---------------------------------------------------------
summary(lm(fpn_modularity_x ~ group * total_ac, data = d))
summary(lm(fpn_efficiency_x ~ group * total_ac, data = d))
summary(lm(fpn_clustering_x ~ group * total_ac, data = d))
summary(lm(fpn_participation_x ~ group * total_ac, data = d))

summary(lm(fpn_modularity_x ~ group + total_ac, data = d))
summary(lm(fpn_efficiency_x ~ group + total_ac, data = d))
summary(lm(fpn_clustering_x ~ group + total_ac, data = d))
summary(lm(fpn_participation_x ~ group + total_ac, data = d))
```
```{r}
library(ggpubr)
d$gr*
lm1 <- lm(fpn_modularity_x ~ group * actphi, data = d) # *
AIC(lm1)
summary(lm1)
#better AIC with just group

summary(lm(fpn_efficiency_x ~ group * actphi, data = d))
summary(lm(fpn_clustering_x ~ group * actphi, data = d)) # *
summary(lm(fpn_participation_x ~ group * actphi, data = d)) # *
summary(lm(fpn_efficiency_x ~ group + actphi, data = d))

p1 <- ggplot(data = d, show.legend = FALSE) + 
  geom_point(aes(x = actupmesor, y = fpn_modularity_x, group = group, color = group), size=2, show.legend = FALSE) + 
  stat_smooth(aes(x = actupmesor, y = fpn_modularity_x, group = group, color = group), method = 'lm', formula = y ~ poly(x,2), se = FALSE, fullrange = FALSE, show.legend = FALSE) +
  theme_minimal() + theme(legend.title = element_blank()) + 
  scale_color_manual(values = brewer.pal(8, "Paired")[7:8]) + 
  xlab('Up-Mesor') + ylab('FPN Modularity')

p2 <- ggplot(data = d) + 
  geom_point(aes(x = actphi, y = fpn_modularity_x, group = group, color = group), size=2, show.legend = FALSE) + 
  stat_smooth(aes(x = actphi, y = fpn_modularity_x, group = group, color = group), method = 'lm', formula = y ~ poly(x,2), se = FALSE, fullrange = FALSE, show.legend = FALSE) +
  theme_minimal() + 
  scale_color_manual(values = brewer.pal(8, "Paired")[7:8]) +
  xlab('Acrophase') + ylab(element_blank())

p3 <- ggplot(data = d) + 
  geom_point(aes(x = actdownmesor, y = fpn_modularity_x, group = group, color = group), size=2, show.legend = FALSE) + 
  stat_smooth(aes(x = actdownmesor, y = fpn_modularity_x, group = group, color = group), method = 'lm', formula = y ~ poly(x,2), se = FALSE, fullrange = FALSE, show.legend = FALSE) +
  theme_minimal() +
  scale_color_manual(values = brewer.pal(8, "Paired")[7:8]) +
  xlab('Down-Mesor') + ylab(element_blank())

ggarrange(p1, p2, p3, heights = c(3, 3, 3), widths = c(8, 8, 8),
          ncol = 3, nrow = 1)

p4 <- ggplot(data = d, show.legend = FALSE) + 
  geom_point(aes(x = actupmesor, y = fpn_participation_x, group = group, color = group), size=2, show.legend = FALSE) + 
  stat_smooth(aes(x = actupmesor, y = fpn_participation_x, group = group, color = group), method = 'lm', formula = y ~ poly(x,2), se = FALSE, fullrange = FALSE, show.legend = FALSE) +
  theme_minimal() + theme(legend.title = element_blank()) + 
  scale_color_manual(values = brewer.pal(8, "Paired")[7:8]) + 
  xlab('Up-Mesor') + ylab('FPN Participation Coefficient')

p5 <- ggplot(data = d) + 
  geom_point(aes(x = actphi, y = fpn_participation_x, group = group, color = group), size=2, show.legend = FALSE) + 
  stat_smooth(aes(x = actphi, y = fpn_participation_x, group = group, color = group), method = 'lm', formula = y ~ poly(x,2), se = FALSE, fullrange = FALSE, show.legend = FALSE) +
  theme_minimal() + 
  scale_color_manual(values = brewer.pal(8, "Paired")[7:8]) +
  xlab('Acrophase') + ylab(element_blank())

p6 <- ggplot(data = d) + 
  geom_point(aes(x = actdownmesor, y = fpn_participation_x, group = group, color = group), size=2, show.legend = FALSE) + 
  stat_smooth(aes(x = actdownmesor, y = fpn_participation_x, group = group, color = group), method = 'lm', formula = y ~ poly(x,2), se = FALSE, fullrange = FALSE, show.legend = FALSE) +
  theme_minimal() +
  scale_color_manual(values = brewer.pal(8, "Paired")[7:8]) +
  xlab('Down-Mesor') + ylab(element_blank())

ggarrange(p4, p5, p6, heights = c(3, 3, 3), widths = c(8, 8, 8),
          ncol = 3, nrow = 1)
```


```{r}
summary(lm(wb_modularity_x ~ group * IS, data = d))
summary(lm(wb_efficiency_x ~ group * IS, data = d))
summary(lm(wb_clustering_x ~ group * IS, data = d))
summary(lm(wb_participation_x ~ group * IS, data = d))

summary(lm(wb_modularity_x ~ group + IS, data = d))
summary(lm(wb_efficiency_x ~ group + IS, data = d))
summary(lm(wb_clustering_x ~ group + IS, data = d))
summary(lm(wb_participation_x ~ group + IS, data = d))

#---------------------------------------------------------

summary(lm(wb_modularity_x ~ group * IV, data = d))
summary(lm(wb_efficiency_x ~ group * IV, data = d))
summary(lm(wb_clustering_x ~ group * IV, data = d))
summary(lm(wb_participation_x ~ group * IV, data = d))

summary(lm(wb_modularity_x ~ group + IV, data = d))
summary(lm(wb_efficiency_x ~ group + IV, data = d))
summary(lm(wb_clustering_x ~ group + IV, data = d))
summary(lm(wb_participation_x ~ group + IV, data = d))

#---------------------------------------------------------

summary(lm(wb_modularity_x ~ group * RA, data = d))
summary(lm(wb_efficiency_x ~ group * RA, data = d))
summary(lm(wb_clustering_x ~ group * RA, data = d))
summary(lm(wb_participation_x ~ group * RA, data = d))

summary(lm(wb_modularity_x ~ group + RA, data = d))
summary(lm(wb_efficiency_x ~ group + RA, data = d))
summary(lm(wb_clustering_x ~ group + RA, data = d))
summary(lm(wb_participation_x ~ group + RA, data = d))

#---------------------------------------------------------
summary(lm(wb_modularity_x ~ group * fact, data = d))
summary(lm(wb_efficiency_x ~ group * fact, data = d))
summary(lm(wb_clustering_x ~ group * fact, data = d))
summary(lm(wb_participation_x ~ group * fact, data = d))

summary(lm(wb_modularity_x ~ group + fact, data = d))
summary(lm(wb_efficiency_x ~ group + fact, data = d))
summary(lm(wb_clustering_x ~ group + fact, data = d))
summary(lm(wb_participation_x ~ group + fact, data = d))

#---------------------------------------------------------

summary(lm(wb_modularity_x ~ group * actamp, data = d))
summary(lm(wb_efficiency_x ~ group * actamp, data = d))
summary(lm(wb_clustering_x ~ group * actamp, data = d))
summary(lm(wb_participation_x ~ group * actamp, data = d))

summary(lm(wb_modularity_x ~ group + actamp, data = d))
summary(lm(wb_efficiency_x ~ group + actamp, data = d))
summary(lm(wb_clustering_x ~ group + actamp, data = d))
summary(lm(wb_participation_x ~ group + actamp, data = d))

#---------------------------------------------------------

summary(lm(wb_modularity_x ~ group * actphi, data = d))
summary(lm(wb_efficiency_x ~ group * actphi, data = d))
summary(lm(wb_clustering_x ~ group * actphi, data = d))
summary(lm(wb_participation_x ~ group * actphi, data = d))

summary(lm(wb_modularity_x ~ group + actphi, data = d))
summary(lm(wb_efficiency_x ~ group + actphi, data = d))
summary(lm(wb_clustering_x ~ group + actphi, data = d))
summary(lm(wb_participation_x ~ group + actphi, data = d))

#---------------------------------------------------------
summary(lm(wb_modularity_x ~ group * sleep_time, data = d))
summary(lm(wb_efficiency_x ~ group * sleep_time, data = d))
summary(lm(wb_clustering_x ~ group * sleep_time, data = d))
summary(lm(wb_participation_x ~ group * sleep_time, data = d))

summary(lm(wb_modularity_x ~ group + sleep_time, data = d))
summary(lm(wb_efficiency_x ~ group + sleep_time, data = d))
summary(lm(wb_clustering_x ~ group + sleep_time, data = d))
summary(lm(wb_participation_x ~ group + sleep_time, data = d))

#---------------------------------------------------------
summary(lm(wb_modularity_x ~ group * efficiency, data = d))
summary(lm(wb_efficiency_x ~ group * efficiency, data = d))
summary(lm(wb_clustering_x ~ group * efficiency, data = d))
summary(lm(wb_participation_x ~ group * efficiency, data = d))

summary(lm(wb_modularity_x ~ group + efficiency, data = d))
summary(lm(wb_efficiency_x ~ group + efficiency, data = d))
summary(lm(wb_clustering_x ~ group + efficiency, data = d))
summary(lm(wb_participation_x ~ group + efficiency, data = d))

#---------------------------------------------------------
summary(lm(wb_modularity_x ~ group * total_ac, data = d))
summary(lm(wb_efficiency_x ~ group * total_ac, data = d))
summary(lm(wb_clustering_x ~ group * total_ac, data = d))
summary(lm(wb_participation_x ~ group * total_ac, data = d))

summary(lm(wb_modularity_x ~ group + total_ac, data = d))
summary(lm(wb_efficiency_x ~ group + total_ac, data = d))
summary(lm(wb_clustering_x ~ group + total_ac, data = d))
summary(lm(wb_participation_x ~ group + total_ac, data = d))
```


```{r bct and cr}
d3.mlt <- melt(select(d, record_id, group, dmn_participation_x, IS:fact, -L5_starttime, -M10_starttime, efficiency:total_ac), id.vars=c('record_id', 'group', 'dmn_participation_x'))

ggplot(data = d3.mlt) + 
  ggtitle('DMN Participation Coefficient and Rest-Activity Measures') + 
  geom_point(aes(x = value, y = dmn_participation_x, group = group, color = group), size=0.5) + 
  #stat_smooth(aes(x = value, y = dmn_participation_x, group = group, color = group), method = 'lm', se = FALSE, fullrange = FALSE) +
  facet_wrap(~ variable,  scales='free') + 
  theme_minimal() +
  scale_color_manual(values = brewer.pal(8, "Paired")[7:8]) +
  xlab(element_blank()) + ylab('DMN Participation Coefficient') +
  theme(axis.text.y = element_blank(), axis.text.x = element_blank())
```

```{r}
ggplot(data = d) + 
  ggtitle('DMN Participation Coefficient and Amplitude') + 
  geom_point(aes(x = actamp, y = dmn_participation_x, group = group, color = group), size=2) + 
  stat_smooth(aes(x = actamp, y = dmn_participation_x, group = group, color = group), method = 'lm', se = FALSE, fullrange = FALSE) +
  theme_minimal() +
  scale_color_manual(values = brewer.pal(8, "Paired")[7:8]) +
  xlab('Amplitude') + ylab('DMN Participation Coefficient') 

ggplot(data = d) + 
  ggtitle('DMN Participation Coefficient and Interdaily Stability') + 
  geom_point(aes(x = IS, y = dmn_participation_x, group = group, color = group), size=2) + 
  stat_smooth(aes(x = IS, y = dmn_participation_x, group = group, color = group), method = 'lm', se = FALSE, fullrange = FALSE) +
  theme_minimal() +
  scale_color_manual(values = brewer.pal(8, "Paired")[7:8]) +
  xlab('IS') + ylab('DMN Participation Coefficient') 

ggplot(data = d) + 
  ggtitle('DMN Participation Coefficient and Total Sleep Time') + 
  geom_point(aes(x = sleep_time, y = dmn_participation_x, group = group, color = group), size=2) + 
  stat_smooth(aes(x = sleep_time, y = dmn_participation_x, group = group, color = group), method = 'lm', se = FALSE, fullrange = FALSE) +
  theme_minimal() +
  scale_color_manual(values = brewer.pal(8, "Paired")[7:8]) +
  xlab('Sleep Time (min)') + ylab('DMN Participation Coefficient') + 
  scale_x_continuous(limits = c(125, 550))

```

```{r}
plot(lm(dmn_participation_x ~ actamp, data = d))
```


```{r}
summary(lm(trails_b_z_score ~ group + actamp, data = d))
plot(lm(trails_b_z_score ~ group + actamp, data = d))

summary(lm(trails_b_z_score ~ group + fact, data = d))
summary(lm(trails_b_z_score ~ fact, data = d))
plot(lm(trails_b_z_score ~ fact, data = d))
```

```{r}
library(corrr)

cor_data <- select(d, dmn_participation_x, cvlt_b_zscore:trails_b_z_score)
cor_data <- data.frame(apply(cor_data, 2, function(x) as.numeric(as.character(x))))
focus_out <- cor_data %>%
  correlate() %>%
  focus(dmn_participation_x) 

focus_out[abs(focus_out[,2]) > 0.2,]

```

```{r}
cor_data <- select(d, fact, cvlt_b_zscore:trails_b_z_score)
cor_data <- data.frame(apply(cor_data, 2, function(x) as.numeric(as.character(x))))
focus_out <- cor_data %>%
  correlate() %>%
  focus(fact) 

focus_out[abs(focus_out[,2]) > 0.15,]
```

```{r participation coefficient}
library(corrr)

pcoef <- read_csv('~/Box/CogNeuroLab/Aging Decision Making R01/Analysis/bct/participation_nodewise.csv', col_names = TRUE )

pcoef <- merge(pcoef, dplyr::select(cr, record_id, IS:RA, fact, actupmesor, actdownmesor, actquot), by = 'record_id')
OA_cor_data <- filter(pcoef, record_id > 40000)
YA_cor_data <- filter(pcoef, record_id < 40000)
record_id <- pcoef$record_id
group <- ifelse(record_id > 40000, 1, 0)

cor_data <- dplyr::select(pcoef, -record_id)
OA_cor_data <- dplyr::select(OA_cor_data, -record_id)
YA_cor_data <- dplyr::select(YA_cor_data, -record_id)

cor_data <- data.frame(apply(pcoef, 2, function(x) as.numeric(as.character(x))))
OA_cor_data <- data.frame(apply(OA_cor_data, 2, function(x) as.numeric(as.character(x))))
YA_cor_data <- data.frame(apply(YA_cor_data, 2, function(x) as.numeric(as.character(x))))

focus_out_all <- cor_data %>%
  correlate() %>%
  focus(IS:RA,fact, actupmesor, actdownmesor, actquot)

focus_out_OA <- OA_cor_data %>%
  correlate() %>%
  focus(IS:RA,fact, actupmesor, actdownmesor, actquot)

focus_out_YA <- YA_cor_data %>%
  correlate() %>%
  focus(IS:RA,fact, actupmesor, actdownmesor, actquot)

#focus_out[abs(focus_out[,4]) > 0.3,]


focus.mlt <- melt(focus_out_all, id.vars = 'rowname')
focus_OA.mlt <- melt(focus_out_OA, id.vars = 'rowname')
focus_YA.mlt <- melt(focus_out_YA, id.vars = 'rowname')

ggplot(data = focus.mlt[abs(focus.mlt$value) > 0.4,], aes(x = value, y = rowname)) + 
  geom_point(color = 'black') + 
  geom_point(data = focus_OA.mlt[abs(focus_OA.mlt$value) > 0.4,], color = 'blue') + 
  geom_point(data = focus_YA.mlt[abs(focus_YA.mlt$value) > 0.4,], color = 'green') +
  facet_grid( ~ variable,  scales='free')
```

```{r}
pcoef <- read_csv('~/Box/CogNeuroLab/Aging Decision Making R01/Analysis/bct/participation_nodewise.csv', col_names = TRUE )

pcoef <- merge(pcoef, dplyr::select(neuro, record_id, vc_zscore, cvlt_ldelay_recall_zscore, cowat_zscore, ds_zscore, trails_b_z_score), by = 'record_id')
OA_cor_data <- filter(pcoef, record_id > 40000)
YA_cor_data <- filter(pcoef, record_id < 40000)
record_id <- pcoef$record_id
group <- ifelse(record_id > 40000, 1, 0)

focus_cog_OA <- OA_cor_data %>%
  correlate() %>%
  focus(vc_zscore, cvlt_ldelay_recall_zscore, cowat_zscore, ds_zscore, trails_b_z_score)

focus_cog_YA <- YA_cor_data %>%
  correlate() %>%
  focus(vc_zscore, cvlt_ldelay_recall_zscore, cowat_zscore, ds_zscore, trails_b_z_score)

focus_cog_OA.mlt <- melt(focus_cog_OA, id.vars = 'rowname')
focus_cog_YA.mlt <- melt(focus_cog_YA, id.vars = 'rowname')

ggplot(data = focus_cog_OA.mlt[abs(focus_cog_OA.mlt$value) > 0.3,], aes(x = value, y = rowname)) + 
  geom_point(color = 'blue') + 
  geom_point(data = focus_cog_YA.mlt[abs(focus_cog_YA.mlt$value) > 0.3,], color = 'green') + 
  facet_grid( ~ variable,  scales='free')
```

```{r}
#vc_zscore, cvlt_ldelay_recall_zscore, cowat_zscore, ds_zscore, trails_b_z_score

summary(lm(cowat_zscore ~ dmn_participation_x, data = d))
summary(lm(vc_zscore ~ dmn_participation_x, data = d)) # *
summary(lm(trails_b_z_score ~ dmn_participation_x, data = d))
summary(lm(ds_backward_score   ~ dmn_participation_x, data = d)) 
summary(lm(ds_zscore   ~ dmn_participation_x, data = d)) 
summary(lm(cvlt_ldelay_recall_zscore  ~ dmn_participation_x, data = d))

summary(lm(RA ~ wb_modularity_x, data = d))
summary(lm(vc_zscore ~ wb_modularity_x, data = d)) #.
summary(lm(trails_b_z_score ~ wb_modularity_x, data = d))
summary(lm(ds_backward_score   ~ wb_modularity_x, data = d)) 
summary(lm(ds_zscore   ~ wb_modularity_x, data = d)) 
summary(lm(cvlt_ldelay_recall_zscore  ~ wb_modularity_x, data = d))

```

