---
title: "Circadian Measures and DTI"
author: "Megan McMahon"
date: "12/3/2019"
output: html_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(readr)
library(corrplot)
library(reshape2)
library(car)

load('~/Box/CogNeuroLab/Aging Decision Making R01/Data/combined_data.RData')
dti <- readxl::read_xlsx('~/Box/CogNeuroLab/Aging Decision Making R01/Analysis/dwi/cr_fa_md.xlsx')
dti <- merge(dti, select(d, record_id, matches("zscore|z_score")), by = "record_id")
d <- c()

d <- select(dti, -fa_mean_3_skel, -fa_mean_4_skel, -fa_mean_5_skel, -md_mean_3_skel, -md_mean_4_skel, -md_mean_5_skel)
d$Group <- factor(ifelse(d$record_id < 40000, 0, 1), label = c("Young Adults", "Older Adults"))
ya_data <- d[d$Group == "Young Adults", ]
oa_data <- d[d$Group == "Older Adults", ]
```


```{r}
# histograms
d %>%
  select(Group, IS:RA, actamp:fact) %>%
  melt(id.vars = "Group") %>%
  ggplot() +
  geom_histogram(aes(x = value, fill = variable)) + 
  facet_wrap(variable ~ Group, scales = "free") +
  xlab("CR") + ylab("Count") 

d %>%
  select(Group, md_mean_3, md_mean_4, md_mean_5) %>%
  melt(id.vars = "Group") %>%
  ggplot() +
  geom_histogram(aes(x = value, fill = variable)) +
  scale_fill_discrete(name = "ROI", labels = c("Genu", "Body", "Splenium")) +
  facet_wrap(Group ~ variable, scales = "free_y") +
  xlab("Mean Diffusivity") + ylab("Count") 

d %>%
  select(Group, fa_mean_3, fa_mean_4, fa_mean_5) %>%
  melt(id.vars = "Group") %>%
  ggplot() +
  geom_histogram(aes(x = value, fill = variable)) +
  scale_fill_discrete(name = "ROI", labels = c("Genu", "Body", "Splenium")) +
  facet_wrap(Group ~ variable, scales = "free_y") +
  xlab("Fractional Anisotropy") + ylab("Count") 

d %>%
  select(Group, fa_mean_sca, md_mean_sca) %>%
  melt(id.vars = "Group") %>%
  ggplot() +
  geom_histogram(aes(x = value, fill = variable)) +
  scale_fill_discrete(name = "ROI", labels = c("FA", "MD")) +
  facet_wrap(Group ~ variable, scales = "free") +
  ylab("Count") 
```


```{r}
# remove actbeta outlier
summary(d$actbeta)
d$record_id[d$actbeta == max(d$actbeta)]
d[d$record_id == 40758,] <- NA

```



```{r}
# correlation plots
alpha = 0.05

ya_mat <- cor(select(ya_data, -record_id, -files, -matches("zscore|z_score"), trails_b_z_score, -Group))
ya_res <- cor.mtest(ya_mat, conf.level = (1-alpha))
corrplot(ya_mat, p.mat = ya_res$p, sig.level = alpha, insig = "blank", type = "upper")

oa_mat <- cor(select(oa_data, -record_id, -files, -Group))
oa_res <- cor.mtest(oa_mat, conf.level = (1-alpha))
corrplot(oa_mat, p.mat = oa_res$p, sig.level = alpha, insig = "blank", type = "upper")
#addCoef.col = TRUE, number.cex = .6
```



```{r}
lm1 <- lm(md_mean_4 ~ age + actalph, data = oa_data)
summary(lm1)
AIC(lm1)
d %>%
  na.omit() %>%
  select(Group, md_mean_3, md_mean_4, md_mean_5, actalph) %>%
  melt(id.vars = c("Group", "actalph")) %>%
  ggplot(aes(color = Group, group = Group)) +
  geom_point(aes(x = actalph, y = value, group = Group, color = Group)) +
  stat_smooth(aes(x = actalph, y = value, group = Group, color= Group), method = "lm") + 
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap(Group ~ variable, scales = "free_y") +
  xlab("Width (alpha)") + ylab("Mean Diffusivity") 
```


```{r}
lm2 <- lm(md_mean_4 ~ age + actwidthratio, data = oa_data)
summary(lm2)
d %>%
  na.omit() %>%
  select(Group, md_mean_3, md_mean_4, md_mean_5, actwidthratio) %>%
  melt(id.vars = c("Group", "actwidthratio")) %>%
  ggplot(aes(color = Group, group = Group)) +
  geom_point(aes(x = actwidthratio, y = value, group = Group, color = Group)) +
  stat_smooth(aes(x = actwidthratio, y = value, group = Group, color= Group), method = "lm") + 
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap(Group ~ variable, scales = "free_y") +
  xlab("Width-ratio") + ylab("Mean Diffusivity") 
```


```{r}
lm3 <- lm(fa_mean_4 ~ age + actalph, data = oa_data)
summary(lm3)
d %>%
  na.omit() %>%
  select(Group, fa_mean_3, fa_mean_4, fa_mean_5, actalph) %>%
  melt(id.vars = c("Group", "actalph")) %>%
  ggplot() +
  geom_point(aes(x = actalph, y = value, group = Group, color = Group)) +
  stat_smooth(aes(x = actalph, y = value, group = Group, color= Group), method = "lm") + 
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap(Group ~ variable, scales = "free_y") +
  xlab("Width (alpha)") + ylab("Fractional Anisotropy") 
```

```{r}
#older adults
#body - highest correlation values

stepdata <- select(oa_data, age, IS:RA, actalph:fact, md_mean_4)
summary(slm02 <- lm(md_mean_4 ~ ., data = stepdata))
slm2 <- step(slm02, direction = "both")
summary(slm2)
AIC(slm2)
```

```{r}
#young adults
#body - highest correlation values
stepdata <- select(ya_data, age, IS:RA, actalph:fact, md_mean_4)
summary(slm02y <- lm(md_mean_4 ~ ., data = stepdata))
slm2y <- step(slm02y, direction = "both")
summary(slm2y)
```


```{r}
# older adults model for MD in body of CC that includes RA has lower AIC
lm1 <- lm(md_mean_4 ~ age + actalph, data = oa_data)
summary(lm1)
AIC(lm1)
AIC(slm2) # <
```


```{r}
library(beset)
stepdata <- select(oa_data, age, IS:RA, actalph:fact, -actwidthratio, fa_mean_4)
mod01 <- (slm02 <- lm(fa_mean_4 ~ ., data = stepdata, direction = "both"))
summary(mod01)

mod <- beset_lm(fa_mean_4 ~ ., data = stepdata, n_folds = 51, force_in = "age")
plot(mod)
#return the model with the smallest number of parameters that is within one standard error of the model with the lowest cross-validation error (the “1-SE rule”).
summary(mod, n_folds = 51)
#without 1-SE rule
summary(mod, oneSE = FALSE, n_folds = 51) #age, RA, alpha
#aic
summary(mod, metric = "aic", n_folds = 51) 
```
```{r}
library(beset)
stepdata <- select(oa_data, age, IS:RA, actalph:fact, -actwidthratio, md_mean_4)

mod <- beset_lm(md_mean_4 ~ ., data = stepdata, n_folds = 51, force_in = "age")
plot(mod)
#return the model with the smallest number of parameters that is within one standard error of the model with the lowest cross-validation error (the “1-SE rule”).
summary(mod, n_folds = 51)
#without 1-SE rule
summary(mod, oneSE = FALSE, n_folds = 51) #age, RA, alpha
#aic
summary(mod, metric = "aic", n_folds = 51) 
```


```{r}
# correlation plots
alpha = 0.05

d$ef <- (d$trails_b_z_score + d$ds_zscore)/2
oa_data <- filter(d, Group == "Older Adults")
oa_mat <- cor(select(oa_data, actalph, actwidthratio, ef, matches("zscore|z_score")))
oa_res <- cor.mtest(oa_mat, conf.level = (1-alpha))
corrplot(oa_mat, p.mat = oa_res$p, sig.level = alpha, insig = "blank", type = "upper")

oa_data <- filter(d, Group == "Older Adults")
oa_mat <- cor(select(oa_data, matches("fa_mean|md_mean"), matches("zscore|z_score")))
oa_res <- cor.mtest(oa_mat, conf.level = (1-alpha))
corrplot(oa_mat, p.mat = oa_res$p, sig.level = alpha, insig = "blank", type = "upper")
#addCoef.col = TRUE, number.cex = .6
```






```{r}
#in older adults, which FA or MD measures are correlated with neuropsych measures?
library(corxplor)
oa_data <- filter(d, Group == "Older Adults")
oa_cor_data <- select(oa_data, matches("fa_mean|md_mean"), matches("zscore|z_score"))
boot <- corxplor::cor_boot(x = oa_cor_data, y = NULL, use = "pairwise", method = "pearson",
                     n_rep = 1000, conf = 0.95, seed = 42, n_cores = NULL)
boot
```

```{r}
#in older adults, which CR measures are correlated with FA or MD?
oa_cor_data <- select(oa_data, IS:RA, actamp:fact, matches("fa_mean|md_mean"))
boot <- corxplor::cor_boot(x = oa_cor_data, y = NULL, use = "pairwise", method = "pearson",
                     n_rep = 1000, conf = 0.95, seed = 42, n_cores = NULL)
boot
```


```{r}
summary(lm(fa_mean_4 ~ cowat_zscore + actalph, data = oa_data))
```



```{r}
pvt <- read_csv("~/Box/CogNeuroLab/Aging Decision Making R01/Analysis/pvt/pvt_stats_2019-12-11.csv")
head(pvt)

ccvol <- read_delim("/Volumes/schnyer/Aging_DecMem/Scan_Data/BIDS/derivatives/freesurfer/aseg_table.txt", delim = "\t")
head(ccvol)

library(stringr)
ccvol$CC_Total <- ccvol$CC_Anterior + ccvol$CC_Central + ccvol$CC_Mid_Anterior + ccvol$CC_Mid_Posterior + ccvol$CC_Posterior
ccvol$record_id <- substr(ccvol$`Measure:volume`, 5, 9)
ccvol$record_id

d2 <- merge(d, ccvol, by = "record_id")
d2 <- merge(d2, pvt, by = "record_id")

alpha = 0.05

oa_data <- filter(d2, Group == "Older Adults")
oa_cor_data <- select(oa_data, age, IS:RA, actamp:fact, matches("cc_"), rt_mean, fs)
oa_mat <- cor(oa_cor_data)
oa_res <- cor.mtest(oa_mat, conf.level = (1-alpha))
corrplot(oa_mat, p.mat = oa_res$p, sig.level = alpha, insig = "blank", type = "upper")

```


```{r}
library(beset)
stepdata <- select(oa_data, age, IS:RA, actalph:fact, -actwidthratio, CC_Total)

mod_cc <- beset_lm(CC_Total ~ ., data = stepdata, n_folds = 51, force_in = "age")
summary(mod_cc, n_folds = 51) #559
summary(mod_cc, n_folds = 51, oneSE = FALSE) #558
plot(mod_cc, n_folds = 51, oneSE = FALSE)
#actalph predicts all FA, MD, and volume of CC
```

```{r}
library(beset)
stepdata <- select(oa_data, age, IS:RA, actalph:fact, -actwidthratio, CC_Total, rt_mean)

mod_cc <- beset_lm(rt_mean ~ ., data = stepdata, n_folds = 51, force_in = "age")
summary(mod_cc, n_folds = 51) #559
summary(mod_cc, n_folds = 51, oneSE = FALSE) #558
plot(mod_cc, n_folds = 51, oneSE = FALSE)
#actalph predicts all FA, MD, and volume of CC
```




```{r}
alpha = 0.05

oa_cor_data <- select(oa_data, matches("zscore|z_score"), matches("cc_"))
oa_mat <- cor(oa_cor_data)
oa_res <- cor.mtest(oa_mat, conf.level = (1-alpha))
corrplot(oa_mat, p.mat = oa_res$p, sig.level = alpha, insig = "blank", type = "upper")

```


```{r}


summary(lm(CC_Total ~ age + RA + actalph, data = oa_data))

oa_data %>%
  ggplot() +
  geom_point(aes(x = actalph, y = CC_Total)) +
  stat_smooth(aes(x = actalph, y = CC_Total), method = "lm") + 
  scale_color_manual(values = c("blue")) +
  xlab("Width (alpha)") + ylab("Corpus Callosum Volume") 
```




```{r junk, include = FALSE}
# d$`Verbal Fluency` <- factor(ifelse(d$cowat_zscore < median(d$cowat_zscore, na.rm = TRUE), 0, 1), labels = c("Low", "High"))
# d$`Fractional Anisotropy` <- factor(ifelse(d$fa_mean_4 < median(d$fa_mean_4, na.rm = TRUE), 0, 1), labels = c("Low", "High"))
# 
# #cowat z score?
# 
# library(beset)
# #http://127.0.0.1:18868/library/beset/doc/validate.html
# 
# beset_lm
# 
# lma <- lm(cowat_zscore ~ actalph, data = d[d$Group == "Older Adults", ])
# summary(lma) #NS
# beset::validate(lma, n_folds = 51)
# 
# 
# lmfa <- lm(cowat_zscore ~ fa_mean_4, data = d[d$Group == "Older Adults", ])
# summary(lmfa)
# beset::validate(lmfa, n_folds = 51) 
# 
# 
# lmafa <- lm(fa_mean_4 ~ actalph, data = d[d$Group == "Older Adults", ])
# summary(lmafa) 
# beset::validate(lmafa, n_folds = 51) 
# 
# d %>%
#   subset(Group == "Older Adults") %>%
#   na.omit() %>%
#   select(`Fractional Anisotropy`, actalph, cowat_zscore) %>%
#   melt(id.vars = c("actalph", "Fractional Anisotropy")) %>%
#   ggplot() +
#   geom_point(aes(x = actalph, y = value, group = `Fractional Anisotropy`, color = `Fractional Anisotropy`)) +
#   stat_smooth(aes(x = actalph, y = value, group = `Fractional Anisotropy`, color= `Fractional Anisotropy`), method = "lm") + 
#   scale_color_manual(values = c("blue", "red")) +
#   facet_wrap(. ~ variable, scales = "free_y") +
#   xlab("Width (alpha)") + ylab("COWAT z-score") 
```
